import { useState, useEffect } from "react";
import {
  collection,
  addDoc,
  getDocs,
  deleteDoc,
  updateDoc,
  doc,
  serverTimestamp,
} from "firebase/firestore";
import { db } from "../firebase";
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  ResponsiveContainer,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  BarChart,
  Bar,
} from "recharts";

export default function CouponsAdminPage({ setPage }) {
  const [coupons, setCoupons] = useState([]);
  const [orders, setOrders] = useState([]); 
  const [auditLogs, setAuditLogs] = useState([]); // Real-time storage repo for tracking execution history
  const [sortBy, setSortBy] = useState("newest");
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(null);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");
  const [revenueTimeframe, setRevenueTimeframe] = useState("30days");

  // Fully matched state definitions extended seamlessly to support advanced criteria
  const [newCoupon, setNewCoupon] = useState({
    code: "",
    type: "percentage",
    category: "General",
    value: "",
    maxDiscount: "",
    minOrder: "",
    usageLimit: "",
    perUserLimit: 1,
    starts: "",
    expires: "",
    singleUse: false,
    active: true,
    // Advanced extensions
    audienceType: "all", // 'all', 'specific_user', 'new_users_only'
    targetUserId: "",
    isAutoGenerated: false,
    triggerType: "manual" // 'manual', 'birthday_event', 'referral_generation'
  });

  const [editCoupon, setEditCoupon] = useState({
    code: "",
    type: "percentage",
    value: "",
    maxDiscount: "",
    minOrder: "",
    category: "General",
    starts: "",
    expires: "",
    usageLimit: "",
    perUserLimit: 1,
    singleUse: false,
    audienceType: "all",
    targetUserId: "",
    triggerType: "manual"
  });

  // --- CORE PRESERVED DATA REDUCERS ---
  const totalUses = coupons.reduce((sum, c) => sum + (c.usageCount || 0), 0);
  const totalPossibleUses = coupons.reduce((sum, c) => sum + (c.usageLimit || 0), 0);
  const redemptionRate = totalPossibleUses > 0 ? ((totalUses / totalPossibleUses) * 100).toFixed(1) : 0;
  const totalDiscount = coupons.reduce((sum, c) => sum + (c.totalDiscountGiven || 0), 0);
  const totalRevenue = coupons.reduce((sum, c) => sum + (c.totalRevenue || 0), 0);

  const mostUsed =
    coupons.length > 0
      ? [...coupons].sort((a, b) => (b.usageCount || 0) - (a.usageCount || 0))[0]
      : null;

  const couponTypes = ["General", "New User", "Festival", "Birthday", "Referral", "Loyalty"];

  const categoryData = couponTypes.map((type) => ({
    name: type,
    value: coupons.filter((c) => (c.category || "General") === type).length,
  }));

  const usageData = [...coupons]
    .sort((a, b) => (a.createdAt?.seconds || 0) - (b.createdAt?.seconds || 0))
    .map((coupon) => ({
      name: coupon.code,
      uses: coupon.usageCount || 0,
    }));

  // --- REVENUE INTERVAL PROCESSOR ENGINE ---
  const salesTodayStats = orders.reduce(
    (stats, order) => {
      const orderDate = order.createdAt?.seconds ? new Date(order.createdAt.seconds * 1000) : null;
      if (orderDate) {
        const today = new Date();
        if (
          orderDate.getDate() === today.getDate() &&
          orderDate.getMonth() === today.getMonth() &&
          orderDate.getFullYear() === today.getFullYear()
        ) {
          stats.count += 1;
          stats.revenue += Number(order.totalPrice || 0);
        }
      }
      return stats;
    },
    { count: 0, revenue: 0 }
  );

  const getFilteredRevenueData = () => {
    const now = new Date();
    let cutoffLimitMs = 30 * 24 * 60 * 60 * 1000;
    let groupingKey = "date";

    if (revenueTimeframe === "14days") cutoffLimitMs = 14 * 24 * 60 * 60 * 1000;
    else if (revenueTimeframe === "7days") cutoffLimitMs = 7 * 24 * 60 * 60 * 1000;
    else if (revenueTimeframe === "3days") cutoffLimitMs = 3 * 24 * 60 * 60 * 1000;
    else if (revenueTimeframe === "48hrs") { cutoffLimitMs = 48 * 60 * 60 * 1000; groupingKey = "hour"; }
    else if (revenueTimeframe === "24hrs") { cutoffLimitMs = 24 * 60 * 60 * 1000; groupingKey = "hour"; }

    const cutoffDate = new Date(now.getTime() - cutoffLimitMs);
    const filtered = orders.filter((o) => {
      const oDate = o.createdAt?.seconds ? new Date(o.createdAt.seconds * 1000) : null;
      return oDate && oDate >= cutoffDate;
    });

    const aggregations = {};
    filtered.forEach((order) => {
      const oDate = new Date(order.createdAt.seconds * 1000);
      const key = groupingKey === "date" 
        ? oDate.toLocaleDateString(undefined, { month: "short", day: "numeric" })
        : `${oDate.getHours()}:00`;
      aggregations[key] = (aggregations[key] || 0) + Number(order.totalPrice || 0);
    });

    return Object.keys(aggregations).map((key) => ({ label: key, amount: aggregations[key] }));
  };

  const revenueDataTimeline = getFilteredRevenueData();
  const totalSalesRevenueCollection = orders.reduce((sum, o) => sum + Number(o.totalPrice || 0), 0);

  // --- AUTOMATIC ALPHANUMERIC STRING ENGINE GENERATOR ---
  function handleGenerateRandomCode() {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    let token = "";
    for (let i = 0; i < 8; i++) {
      token += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    const prefix = newCoupon.category.substring(0, 3).toUpperCase();
    setNewCoupon({ ...newCoupon, code: `${prefix}-${token}`, isAutoGenerated: true });
  }

  // --- DATA OPERATIONS SYNC ---
  async function loadCoupons() {
    try {
      const couponSnapshot = await getDocs(collection(db, "coupons"));
      setCoupons(couponSnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })));
      
      const orderSnapshot = await getDocs(collection(db, "orders"));
      setOrders(orderSnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })));

      try {
        const logSnapshot = await getDocs(collection(db, "coupon_audit_logs"));
        setAuditLogs(logSnapshot.docs.map(d => ({ id: d.id, ...d.data() })).sort((a,b) => (b.timestamp?.seconds || 0) - (a.timestamp?.seconds || 0)));
      } catch (e) {
        // Fallback trace block if audit collection is completely empty inside initialization phase
        setAuditLogs([]);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadCoupons();
  }, []);

  async function createAuditEntry(actionType, couponCode, metadata = {}) {
    try {
      await addDoc(collection(db, "coupon_audit_logs"), {
        action: actionType,
        code: couponCode,
        timestamp: new Date(),
        user: "Admin Operator",
        ...metadata
      });
    } catch (e) {
      console.error("Log compilation trace failed:", e);
    }
  }

  async function addCoupon() {
    if (!newCoupon.code || !newCoupon.value || !newCoupon.minOrder) {
      alert("Please complete all required fields.");
      return;
    }

    const payload = {
      code: newCoupon.code.toUpperCase(),
      type: newCoupon.type,
      category: newCoupon.category,
      value: Number(newCoupon.value),
      maxDiscount: Number(newCoupon.maxDiscount || 0),
      minOrder: Number(newCoupon.minOrder),
      active: newCoupon.active,
      usageLimit: Number(newCoupon.usageLimit || 0),
      usageCount: 0,
      starts: newCoupon.starts,
      expires: newCoupon.expires,
      singleUse: newCoupon.singleUse,
      perUserLimit: Number(newCoupon.perUserLimit),
      audienceType: newCoupon.audienceType,
      targetUserId: newCoupon.audienceType === "specific_user" ? newCoupon.targetUserId : "",
      triggerType: newCoupon.triggerType,
      createdAt: serverTimestamp(),
    };

    await addDoc(collection(db, "coupons"), payload);
    await createAuditEntry("CREATE_CAMPAIGN", payload.code, { category: payload.category, trigger: payload.triggerType });

    setNewCoupon({
      code: "",
      type: "percentage",
      category: "General",
      value: "",
      maxDiscount: "",
      minOrder: "",
      usageLimit: "",
      starts: "",
      expires: "",
      singleUse: false,
      perUserLimit: 1,
      active: true,
      audienceType: "all",
      targetUserId: "",
      isAutoGenerated: false,
      triggerType: "manual"
    });

    loadCoupons();
    alert("Coupon created successfully!");
  }

  async function deleteCoupon(id) {
    if (!window.confirm("Delete this coupon?")) return;
    const historicalDoc = coupons.find(c => c.id === id);
    await deleteDoc(doc(db, "coupons", id));
    if (historicalDoc) {
      await createAuditEntry("DELETE_CAMPAIGN", historicalDoc.code);
    }
    loadCoupons();
  }

  async function toggleCoupon(coupon) {
    const nextState = !coupon.active;
    await updateDoc(doc(db, "coupons", coupon.id), { active: nextState });
    await createAuditEntry(nextState ? "ENABLE_CAMPAIGN" : "DISABLE_CAMPAIGN", coupon.code);
    loadCoupons();
  }

  async function updateCoupon() {
    if (!editing) return;

    await updateDoc(doc(db, "coupons", editing.id), {
      code: editCoupon.code.toUpperCase(),
      type: editCoupon.type,
      value: Number(editCoupon.value),
      maxDiscount: Number(editCoupon.maxDiscount),
      minOrder: Number(editCoupon.minOrder),
      category: editCoupon.category,
      starts: editCoupon.starts,
      expires: editCoupon.expires,
      usageLimit: Number(editCoupon.usageLimit),
      perUserLimit: Number(editCoupon.perUserLimit),
      singleUse: editCoupon.singleUse,
      audienceType: editCoupon.audienceType,
      targetUserId: editCoupon.audienceType === "specific_user" ? editCoupon.targetUserId : "",
      triggerType: editCoupon.triggerType
    });

    await createAuditEntry("UPDATE_METADATA", editCoupon.code.toUpperCase());
    alert("Coupon updated!");
    setEditing(null);
    loadCoupons();
  }

  // --- CARD & BADGE BUILDERS ---
  function StatCard({ title, value, color, icon, highlight }) {
    return (
      <div
        style={{
          background: highlight ? "linear-gradient(135deg, #3B1A08 0%, #522711 100%)" : "#fff",
          padding: "25px",
          borderRadius: "20px",
          boxShadow: "0 10px 25px rgba(0,0,0,.04)",
          border: highlight ? "none" : "1px solid rgba(230, 220, 210, 0.4)",
          display: "flex",
          alignItems: "center",
          gap: "20px",
        }}
      >
        <div style={{ fontSize: "32px", background: highlight ? "rgba(255,255,255,0.1)" : `${color}12`, padding: "12px", borderRadius: "12px" }}>
          {icon}
        </div>
        <div>
          <p style={{ color: highlight ? "#C4956A" : "#777", margin: 0, fontSize: "14px", fontWeight: "500" }}>{title}</p>
          <h1 style={{ marginTop: "4px", marginBottom: 0, color: highlight ? "#fff" : color, fontSize: "28px", fontWeight: "700" }}>{value}</h1>
        </div>
      </div>
    );
  }

  function getCategoryColor(category) {
    switch (category) {
      case "New User": return { bg: "#E3F2FD", color: "#1565C0" };
      case "Festival": return { bg: "#FFF3E0", color: "#EF6C00" };
      case "Birthday": return { bg: "#FCE4EC", color: "#C2185B" };
      case "Referral": return { bg: "#E8F5E9", color: "#2E7D32" };
      case "Loyalty": return { bg: "#F3E5F5", color: "#6A1B9A" };
      default: return { bg: "#ECEFF1", color: "#455A64" };
    }
  }

  function getExpiryStatus(expires, starts) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    if (starts) {
      const activationDate = new Date(starts);
      activationDate.setHours(0, 0, 0, 0);
      if (activationDate > today) {
        const waitDays = Math.ceil((activationDate - today) / (1000 * 60 * 60 * 24));
        return `📅 Scheduled: Activates in ${waitDays} day${waitDays > 1 ? "s" : ""}`;
      }
    }

    if (!expires) return "Never Expires";
    const expiry = new Date(expires);
    expiry.setHours(0, 0, 0, 0);
    const days = Math.ceil((expiry - today) / (1000 * 60 * 60 * 24));
    if (days < 0) return `❌ Expired ${Math.abs(days)} day${Math.abs(days) !== 1 ? "s" : ""} ago`;
    if (days === 0) return "⚠️ Expires Today";
    if (days === 1) return "⏳ Expires Tomorrow";
    return `⏳ Expires in ${days} days`;
  }

  const COLORS = ["#C4956A", "#4F46E5", "#2E7D32", "#F59E0B", "#EC4899", "#06B6D4"];

  const formInputWrapperStyle = {
    padding: "12px 16px",
    borderRadius: "12px",
    border: "1px solid #E6DCD2",
    width: "100%",
    boxSizing: "border-box",
    fontSize: "14px",
    background: "#FCFBFA",
    outline: "none"
  };

  return (
    <div style={{ minHeight: "100vh", background: "#FDFAF5", padding: "60px 4%", fontFamily: "system-ui, sans-serif" }}>
      
      {/* Top Controls Action Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "35px" }}>
        <div>
          <button onClick={() => setPage("admin")} style={{ background: "#fff", border: "1px solid #E6DCD2", padding: "10px 20px", borderRadius: "10px", cursor: "pointer", fontWeight: "500", color: "#5C544E" }}>
            ← Back Dashboard
          </button>
          <h1 style={{ fontFamily: "Playfair Display, serif", marginTop: "20px", marginBottom: 0, fontSize: "36px", color: "#2C2520" }}>
            🎟 Enterprise Coupon Control Center
          </h1>
        </div>
      </div>

      {/* NEW INTEGRATED TRANSACTIONAL OVERVIEWS */}
      <h4 style={{ color: "#7A5A3E", textTransform: "uppercase", letterSpacing: "1px", margin: "0 0 15px 0", fontSize: "13px" }}>
        ⚡ Live Commercial Sales Performance
      </h4>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "20px", marginBottom: "45px" }}>
        <StatCard title="Sales Confirmed Today" value={`${salesTodayStats.count} Transactions`} color="#fff" icon="🛍️" highlight={true} />
        <StatCard title="Revenue Captured Today" value={`₹${salesTodayStats.revenue}`} color="#009688" icon="⚡" />
        <StatCard title="All-Time Total Revenue" value={`₹${totalSalesRevenueCollection}`} color="#2E7D32" icon="💼" />
        <StatCard title="Active System Coupons" value={coupons.filter(c => c.active).length} color="#3B1A08" icon="🎟️" />
      </div>

      {/* VISUAL REPORT SECTIONS ROW */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(420px, 1fr))", gap: "25px", marginBottom: "40px" }}>
        
        {/* Sales Dynamic Revenue Chart Widget */}
        <div style={{ background: "#fff", borderRadius: "20px", padding: "25px", boxShadow: "0 10px 25px rgba(0,0,0,.03)", border: "1px solid #E6DCD2" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
            <h2 style={{ fontFamily: "Playfair Display", margin: 0, fontSize: "20px" }}>💰 Gross Revenue Output</h2>
            <select value={revenueTimeframe} onChange={(e) => setRevenueTimeframe(e.target.value)} style={{ padding: "8px 12px", borderRadius: "8px", border: "1px solid #E6DCD2", fontWeight: "600", fontSize: "13px" }}>
              <option value="30days">📅 Last 30 Days</option>
              <option value="14days">📅 Last 14 Days</option>
              <option value="7days">📅 Last 7 Days</option>
              <option value="3days">📆 Last 3 Days</option>
              <option value="48hrs">⏳ Last 48 Hours</option>
              <option value="24hrs">⏳ Last 24 Hours</option>
            </select>
          </div>
          <ResponsiveContainer width="100%" height={260}>
            {revenueDataTimeline.length > 0 ? (
              <BarChart data={revenueDataTimeline}>
                <CartesianGrid strokeDasharray="3 3" stroke="#F0EAE4" />
                <XAxis dataKey="label" stroke="#A39C96" style={{ fontSize: "11px" }} />
                <YAxis stroke="#A39C96" style={{ fontSize: "11px" }} />
                <Tooltip formatter={(v) => [`₹${v}`, "Revenue"]} />
                <Bar dataKey="amount" fill="#3B1A08" borderRadius={[4, 4, 0, 0]} />
              </BarChart>
            ) : (
              <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: "100%", color: "#999" }}>No data points inside window parameters</div>
            )}
          </ResponsiveContainer>
        </div>

        {/* Categories Pie Panel */}
        <div style={{ background: "#fff", borderRadius: "20px", padding: "25px", boxShadow: "0 10px 25px rgba(0,0,0,.03)", border: "1px solid #E6DCD2" }}>
          <h2 style={{ fontFamily: "Playfair Display, serif", margin: "0 0 20px 0", fontSize: "20px" }}>🥧 Coupon Categories Allocation</h2>
          <ResponsiveContainer width="100%" height={240}>
            <PieChart>
              <Pie data={categoryData} dataKey="value" nameKey="name" outerRadius={85} innerRadius={60} paddingAngle={4} label>
                {categoryData.map((entry, index) => <Cell key={index} fill={COLORS[index % COLORS.length]} />)}
              </Pie>
              <Tooltip />
              <Legend wrapperStyle={{ fontSize: "12px" }} />
            </PieChart>
          </ResponsiveContainer>
        </div>

        {/* Volume Trend Line Chart Panel */}
        <div style={{ background: "#fff", borderRadius: "20px", padding: "25px", boxShadow: "0 10px 25px rgba(0,0,0,.03)", border: "1px solid #E6DCD2", gridColumn: "span 2" }}>
          <h2 style={{ fontFamily: "Playfair Display, serif", margin: "0 0 20px 0", fontSize: "20px" }}>📈 Historic Volume Redemption Trend Curve</h2>
          <ResponsiveContainer width="100%" height={240}>
            <LineChart data={usageData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#F0EAE4" />
              <XAxis dataKey="name" stroke="#A39C96" style={{ fontSize: "11px" }} />
              <YAxis stroke="#A39C96" style={{ fontSize: "11px" }} />
              <Tooltip />
              <Line type="monotone" dataKey="uses" stroke="#C4956A" strokeWidth={3} dot={{ r: 4 }} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* ORIGINAL COMPILATION OF HISTORICAL METRIC STATCARDS */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "20px", marginBottom: "45px" }}>
        <StatCard title="Coupons Stored" value={coupons.length} color="#3B1A08" icon="🎟" />
        <StatCard title="Active Systems" value={coupons.filter(c => c.active).length} color="#2E7D32" icon="✅" />
        <StatCard title="Total Applied Redemptions" value={totalUses} color="#C4956A" icon="🔥" />
        <StatCard title="Aggregated Value Given" value={`₹${totalDiscount}`} color="#4F46E5" icon="💸" />
        <StatCard title="Redemption Rate Scale" value={`${redemptionRate}%`} color="#FF9800" icon="📈" />
        <StatCard title="Attached Revenue Attribute" value={`₹${totalRevenue}`} color="#009688" icon="💰" />
      </div>

      {/* TOP PERFORMING SPOT BANNER */}
      {mostUsed && (
        <div style={{ background: "#fff", borderRadius: "20px", padding: "30px", marginBottom: "40px", boxShadow: "0 10px 25px rgba(0,0,0,.04)", border: "1px solid #E6DCD2" }}>
          <h3 style={{ fontFamily: "Playfair Display", margin: "0 0 10px 0", color: "#3B1A08" }}>🏆 Most Used Configuration Instance</h3>
          <h1 style={{ fontSize: "36px", margin: "5px 0", fontFamily: "monospace" }}>{mostUsed.code}</h1>
          <p style={{ margin: 0, color: "#5C544E" }}>Registered usage profile is applied <strong style={{ color: "#3B1A08" }}>{mostUsed.usageCount || 0}</strong> times consecutively.</p>
        </div>
      )}

      {/* TWO WORKSPACE ROW GRID SYSTEM SPLIT */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))", gap: "30px", alignItems: "start" }}>
        
        {/* LEFT COLUMN PANEL: FORM BUILDERS AND EDITING WRAPPERS */}
        <div style={{ display: "flex", flexDirection: "column", gap: "30px" }}>
          
          {/* COMPLETE UNALTERED CREATOR PANEL WITH NEW SUB-FIELDS */}
          <div style={{ background: "#fff", borderRadius: "22px", padding: "30px", boxShadow: "0 10px 30px rgba(0,0,0,.05)", border: "1px solid #E6DCD2" }}>
            <h2 style={{ fontFamily: "Playfair Display, serif", margin: "0 0 25px 0" }}>✨ Create New Coupon</h2>
            
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              
              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Category Rule Matrix</label>
                <select style={formInputWrapperStyle} value={newCoupon.category} onChange={(e) => setNewCoupon({ ...newCoupon, category: e.target.value })}>
                  <option value="General">🏷 General</option>
                  <option value="New User">👤 First-Order / New User</option>
                  <option value="Festival">🎉 Festival Event</option>
                  <option value="Birthday">🎂 Birthday Specific</option>
                  <option value="Referral">🤝 Referral Reward</option>
                  <option value="Loyalty">💎 Loyalty Milestone</option>
                </select>
              </div>

              <div>
                <label style={{ display: "flex", justifyContent: "space-between", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>
                  <span>Coupon Code *</span>
                  <span onClick={handleGenerateRandomCode} style={{ color: "#4F46E5", cursor: "pointer", textDecoration: "underline" }}>⚙️ Auto-Generate Code</span>
                </label>
                <input style={formInputWrapperStyle} placeholder="e.g. FESTIVAL20" value={newCoupon.code} onChange={(e) => setNewCoupon({ ...newCoupon, code: e.target.value.toUpperCase(), isAutoGenerated: false })} />
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Target Audience (Customer-Specific Filter)</label>
                <select style={formInputWrapperStyle} value={newCoupon.audienceType} onChange={(e) => setNewCoupon({ ...newCoupon, audienceType: e.target.value })}>
                  <option value="all">🌐 Open Public (All Users)</option>
                  <option value="new_users_only">🆕 First-Order Accounts Only</option>
                  <option value="specific_user">👤 Customer-Specific (Individual ID)</option>
                </select>
              </div>

              {newCoupon.audienceType === "specific_user" && (
                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Target Customer User ID *</label>
                  <input style={formInputWrapperStyle} placeholder="e.g. usr_98x2j318b" value={newCoupon.targetUserId} onChange={(e) => setNewCoupon({ ...newCoupon, targetUserId: e.target.value })} />
                </div>
              )}

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Automation Trigger Type</label>
                <select style={formInputWrapperStyle} value={newCoupon.triggerType} onChange={(e) => setNewCoupon({ ...newCoupon, triggerType: e.target.value })}>
                  <option value="manual">Manual Direct Assignment</option>
                  <option value="birthday_event">🎂 Auto-Issue on User Birthday</option>
                  <option value="referral_generation">🤝 Auto-Issue via Referral Link Click</option>
                </select>
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Usage Allocation Type</label>
                <select style={formInputWrapperStyle} value={newCoupon.singleUse ? "single" : "multi"} onChange={(e) => setNewCoupon({ ...newCoupon, singleUse: e.target.value === "single" })}>
                  <option value="multi">🔄 Multi Use</option>
                  <option value="single">1️⃣ Single Use</option>
                </select>
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Discount Pricing Calculations</label>
                <select style={formInputWrapperStyle} value={newCoupon.type} onChange={(e) => setNewCoupon({ ...newCoupon, type: e.target.value })}>
                  <option value="percentage">Percentage (%)</option>
                  <option value="fixed">Fixed Amount (₹)</option>
                </select>
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Discount Value *</label>
                <input type="number" style={formInputWrapperStyle} placeholder="e.g. 15" value={newCoupon.value} onChange={(e) => setNewCoupon({ ...newCoupon, value: e.target.value })} />
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Maximum Absolute Discount Cap (₹)</label>
                <input type="number" style={formInputWrapperStyle} placeholder="Capped maximum fallback" value={newCoupon.maxDiscount} onChange={(e) => setNewCoupon({ ...newCoupon, maxDiscount: e.target.value })} />
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Minimum Order Valuation Constraint (₹) *</label>
                <input type="number" style={formInputWrapperStyle} placeholder="Order base constraint" value={newCoupon.minOrder} onChange={(e) => setNewCoupon({ ...newCoupon, minOrder: e.target.value })} />
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Global Usage Threshold Cap Limit</label>
                <input type="number" style={formInputWrapperStyle} placeholder="Total absolute usage instances allowed" value={newCoupon.usageLimit} onChange={(e) => setNewCoupon({ ...newCoupon, usageLimit: e.target.value })} />
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Per User Direct Usage Allocation Cap</label>
                <input type="number" style={formInputWrapperStyle} value={newCoupon.perUserLimit} onChange={(e) => setNewCoupon({ ...newCoupon, perUserLimit: e.target.value })} />
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Scheduled Activation Date (Delayed Launch)</label>
                <input type="date" style={formInputWrapperStyle} value={newCoupon.starts} onChange={(e) => setNewCoupon({ ...newCoupon, starts: e.target.value })} />
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Campaign Execution Terminus Expiry Date</label>
                <input type="date" style={formInputWrapperStyle} value={newCoupon.expires} onChange={(e) => setNewCoupon({ ...newCoupon, expires: e.target.value })} />
              </div>

              <button onClick={addCoupon} style={{ background: "#3B1A08", color: "#fff", border: "none", padding: "14px 24px", borderRadius: "12px", cursor: "pointer", fontWeight: "600", marginTop: "10px" }}>
                ➕ Create Configured Coupon
              </button>
            </div>
          </div>

          {/* COMPLETE UNALTERED EDIT WORKSPACE EXTENDED */}
          {editing && (
            <div style={{ background: "#fff", padding: "30px", borderRadius: "20px", boxShadow: "0 10px 30px rgba(0,0,0,.08)", border: "2px solid #C4956A" }}>
              <h2 style={{ fontFamily: "Playfair Display, serif", margin: "0 0 20px 0" }}>✏️ Edit Coupon Parameters</h2>
              
              <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Coupon Code</label>
                  <input style={formInputWrapperStyle} value={editCoupon.code} onChange={(e) => setEditCoupon({ ...editCoupon, code: e.target.value.toUpperCase() })} />
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Audience Constraint</label>
                  <select style={formInputWrapperStyle} value={editCoupon.audienceType} onChange={(e) => setEditCoupon({ ...editCoupon, audienceType: e.target.value })}>
                    <option value="all">🌐 Open Public</option>
                    <option value="new_users_only">🆕 First-Order Accounts</option>
                    <option value="specific_user">👤 Customer Specific</option>
                  </select>
                </div>

                {editCoupon.audienceType === "specific_user" && (
                  <div>
                    <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Target User ID</label>
                    <input style={formInputWrapperStyle} value={editCoupon.targetUserId} onChange={(e) => setEditCoupon({ ...editCoupon, targetUserId: e.target.value })} />
                  </div>
                )}

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Type Form</label>
                  <select style={formInputWrapperStyle} value={editCoupon.type} onChange={(e) => setEditCoupon({ ...editCoupon, type: e.target.value })}>
                    <option value="percentage">Percentage</option>
                    <option value="fixed">Fixed Amount</option>
                  </select>
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Category Type</label>
                  <select style={formInputWrapperStyle} value={editCoupon.category} onChange={(e) => setEditCoupon({ ...editCoupon, category: e.target.value })}>
                    <option value="General">General</option>
                    <option value="New User">New User</option>
                    <option value="Festival">Festival</option>
                    <option value="Birthday">Birthday</option>
                    <option value="Referral">Referral</option>
                    <option value="Loyalty">Loyalty</option>
                  </select>
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Discount Value Metric</label>
                  <input type="number" style={formInputWrapperStyle} value={editCoupon.value} onChange={(e) => setEditCoupon({ ...editCoupon, value: e.target.value })} />
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Maximum Discount Capping (₹)</label>
                  <input type="number" style={formInputWrapperStyle} value={editCoupon.maxDiscount} onChange={(e) => setEditCoupon({ ...editCoupon, maxDiscount: e.target.value })} />
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Minimum Order Bounds</label>
                  <input type="number" style={formInputWrapperStyle} value={editCoupon.minOrder} onChange={(e) => setEditCoupon({ ...editCoupon, minOrder: e.target.value })} />
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Usage Type Target</label>
                  <select style={formInputWrapperStyle} value={editCoupon.singleUse ? "single" : "multi"} onChange={(e) => setEditCoupon({ ...editCoupon, singleUse: e.target.value === "single" })}>
                    <option value="multi">🔄 Multi Use</option>
                    <option value="single">1️⃣ Single Use</option>
                  </select>
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Global Threshold Cap Limit</label>
                  <input type="number" style={formInputWrapperStyle} value={editCoupon.usageLimit} onChange={(e) => setEditCoupon({ ...editCoupon, usageLimit: e.target.value })} />
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Per User Cap Allocation</label>
                  <input type="number" min="1" style={formInputWrapperStyle} value={editCoupon.perUserLimit} onChange={(e) => setEditCoupon({ ...editCoupon, perUserLimit: e.target.value })} />
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Starts Release Window</label>
                  <input type="date" style={formInputWrapperStyle} value={editCoupon.starts} onChange={(e) => setEditCoupon({ ...editCoupon, starts: e.target.value })} />
                </div>

                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Terminus Expiry Bounds</label>
                  <input type="date" style={formInputWrapperStyle} value={editCoupon.expires} onChange={(e) => setEditCoupon({ ...editCoupon, expires: e.target.value })} />
                </div>

                <div style={{ display: "flex", gap: "10px", marginTop: "10px" }}>
                  <button onClick={updateCoupon} style={{ flex: 1, background: "#2E7D32", color: "#fff", border: "none", padding: "12px 20px", borderRadius: "10px", fontWeight: "600", cursor: "pointer" }}>
                    💾 Save Configurations
                  </button>
                  <button onClick={() => setEditing(null)} style={{ background: "#FAF7F2", border: "1px solid #E6DCD2", padding: "12px 20px", borderRadius: "10px", cursor: "pointer" }}>
                    Cancel
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* RIGHT COLUMN PANEL: PORTFOLIO RENDERING WITH EVERY FILTER & INLINE FIELD */}
        <div style={{ gridColumn: "span 2" }}>
          
          {/* Controls Filtration Hub Bar */}
          <div style={{ display: "flex", gap: "15px", marginBottom: "25px", flexWrap: "wrap" }}>
            <input type="text" placeholder="🔍 Search matching criteria code portfolios..." value={search} onChange={(e) => setSearch(e.target.value)} style={{ ...formInputWrapperStyle, flex: 1, minWidth: "250px", padding: "14px" }} />
            
            <select value={filter} onChange={(e) => setFilter(e.target.value)} style={{ ...formInputWrapperStyle, width: "auto" }}>
              <option value="All">All Structural Filter Statuses</option>
              <option value="Active">Active States Only</option>
              <option value="Disabled">Disabled States Only</option>
              <option value="Expired">Expired States Only</option>
            </select>
            
            <select value={sortBy} onChange={(e) => setSortBy(e.target.value)} style={{ ...formInputWrapperStyle, width: "auto" }}>
              <option value="newest">📅 Order: Newest Created</option>
              <option value="code">🔤 Order: Alphabetical Code (A-Z)</option>
              <option value="used">🔥 Order: Most Redemptions Logged</option>
              <option value="expiry">⏳ Order: Terminus Expiring First</option>
            </select>
          </div>

          <h2 style={{ fontFamily: "Playfair Display, serif", marginBottom: "20px" }}>🎟 Active Operational Repositories</h2>

          {loading ? (
            <p style={{ color: "#777" }}>Synchronizing repository data sheets...</p>
          ) : coupons.length === 0 ? (
            <div style={{ background: "#fff", padding: "40px", borderRadius: "20px", textAlign: "center", border: "1px solid #E6DCD2" }}>
              <h3>No coupons created yet.</h3>
              <p style={{ color: "#777" }}>Deploy your first tracking tracking parameters above.</p>
            </div>
          ) : (
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: "20px", marginBottom: "40px" }}>
              {coupons
                .filter((coupon) => {
                  const matchesSearch = coupon.code.toLowerCase().includes(search.toLowerCase());
                  let matchesFilter = true;
                  if (filter === "Active") matchesFilter = coupon.active;
                  if (filter === "Disabled") matchesFilter = !coupon.active;
                  if (filter === "Expired") matchesFilter = coupon.expires && new Date(coupon.expires) < new Date();
                  return matchesSearch && matchesFilter;
                })
                .sort((a, b) => {
                  switch (sortBy) {
                    case "code": return a.code.localeCompare(b.code);
                    case "used": return (b.usageCount || 0) - (a.usageCount || 0);
                    case "expiry": return new Date(a.expires || "9999-12-31") - new Date(b.expires || "9999-12-31");
                    default: return (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0);
                  }
                })
                .map((coupon) => {
                  const badge = getCategoryColor(coupon.category);
                  return (
                    <div key={coupon.id} style={{ background: "#fff", borderRadius: "20px", padding: "24px", boxShadow: "0 10px 25px rgba(0,0,0,.03)", border: "1px solid #E6DCD2", display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
                      <div>
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "15px" }}>
                          <h2 style={{ margin: 0, fontFamily: "monospace", fontWeight: "700" }}>{coupon.code}</h2>
                          <span style={{ background: coupon.active ? "#E8F5E9" : "#FFEBEE", color: coupon.active ? "#2E7D32" : "#C62828", padding: "6px 12px", borderRadius: 999, fontWeight: 600, fontSize: 13 }}>
                            {coupon.active ? "● Active" : "○ Disabled"}
                          </span>
                        </div>

                        <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginBottom: "12px" }}>
                          <span style={{ display: "inline-block", padding: "4px 10px", borderRadius: "6px", fontWeight: "600", fontSize: "11px", background: badge.bg, color: badge.color, textTransform: "uppercase" }}>
                            {coupon.category || "General"}
                          </span>
                          
                          {/* Audience Target Label Tags Indicator Row */}
                          <span style={{ fontSize: "11px", fontWeight: "600", padding: "4px 10px", borderRadius: "6px", background: "#FAF0E6", color: "#8B4513" }}>
                            {coupon.audienceType === "specific_user" ? `👤 Only: ${coupon.targetUserId}` : coupon.audienceType === "new_users_only" ? "🆕 First-Order Target" : "🌐 Public Open Tier"}
                          </span>
                        </div>

                        <div style={{ display: "flex", flexDirection: "column", gap: "6px", fontSize: "14px", color: "#2C2520" }}>
                          <p style={{ margin: 0 }}><strong>Usage Allocation Type:</strong> {coupon.singleUse ? "1️⃣ Single Use Only" : "🔄 Reusable Mechanism"}</p>
                          <p style={{ margin: 0 }}><strong>Discount Matrix Rate:</strong> {coupon.type === "percentage" ? `${coupon.value}%` : `₹${coupon.value}`}{coupon.type === "percentage" && coupon.maxDiscount > 0 && ` (Up to ₹${coupon.maxDiscount})`}</p>
                          <p style={{ margin: 0 }}><strong>Minimum Order Evaluation Bounds:</strong> ₹{coupon.minOrder}</p>
                          <p style={{ margin: 0 }}><strong>Usage Limit Scale Capacity:</strong> {coupon.usageCount || 0} / {coupon.usageLimit || "∞"}</p>
                          <p style={{ margin: 0 }}><strong>Per User Cap Allocation:</strong> {coupon.perUserLimit || 1} use{coupon.perUserLimit > 1 ? "s" : ""}</p>
                          <p style={{ margin: 0 }}><strong>Scheduled Active Launch:</strong> {coupon.starts || "Immediate Execution"}</p>
                          <p style={{ margin: 0 }}><strong>Terminus Expiry Bounds:</strong> {coupon.expires || "Infinite Lifecycle"}</p>
                        </div>

                        <p style={{ fontWeight: "600", fontSize: "13px", marginTop: "14px", marginBottom: 0, color: coupon.expires && new Date(coupon.expires) < new Date() ? "#D32F2F" : "#7A5A3E" }}>
                          {getExpiryStatus(coupon.expires, coupon.starts)}
                        </p>
                      </div>

                      {/* Lower Actions Board Container */}
                      <div style={{ display: "flex", gap: "10px", marginTop: "20px", borderTop: "1px dashed #E6DCD2", paddingTop: "16px" }}>
                        <button onClick={() => toggleCoupon(coupon)} style={{ flex: 1, background: coupon.active ? "#F5B942" : "#2E7D32", color: "#fff", border: "none", padding: "10px", borderRadius: "10px", cursor: "pointer", fontWeight: "600" }}>
                          {coupon.active ? "Disable" : "Enable"}
                        </button>
                        <button
                          onClick={() => {
                            setEditing(coupon);
                            setEditCoupon({
                              code: coupon.code,
                              type: coupon.type,
                              value: coupon.value,
                              maxDiscount: coupon.maxDiscount || "",
                              minOrder: coupon.minOrder,
                              category: coupon.category || "General",
                              starts: coupon.starts || "",
                              expires: coupon.expires || "",
                              usageLimit: coupon.usageLimit || "",
                              perUserLimit: coupon.perUserLimit || 1,
                              singleUse: coupon.singleUse || false,
                              audienceType: coupon.audienceType || "all",
                              targetUserId: coupon.targetUserId || "",
                              triggerType: coupon.triggerType || "manual"
                            });
                          }}
                          style={{ flex: 1, background: "#C4956A", color: "#fff", border: "none", padding: "10px", borderRadius: "10px", cursor: "pointer", fontWeight: "600" }}
                        >
                          ✏ Edit
                        </button>
                        <button onClick={() => deleteCoupon(coupon.id)} style={{ flex: 1, background: "#D32F2F", color: "#fff", border: "none", padding: "10px", borderRadius: "10px", cursor: "pointer", fontWeight: "600" }}>
                          Delete
                        </button>
                      </div>

                    </div>
                  );
                })}
            </div>
          )}

          {/* DYNAMIC HISTORICAL DATA AUDIT LOG DATAGRID TABLE */}
          <div style={{ background: "#fff", borderRadius: "20px", padding: "25px", border: "1px solid #E6DCD2", boxShadow: "0 4px 20px rgba(0,0,0,0.02)" }}>
            <h2 style={{ fontFamily: "Playfair Display, serif", margin: "0 0 6px 0", fontSize: "20px" }}>📜 Coupon History & System Audit Log</h2>
            <p style={{ color: "#777", fontSize: "13px", margin: "0 0 20px 0" }}>Immutably recording deployment lifecycles, configuration modifications, and core promotional adjustments.</p>
            
            <div style={{ overflowX: "auto", maxHeight: "300px" }}>
              <table style={{ width: "100%", borderCollapse: "collapse", textStyle: "left", fontSize: "13px" }}>
                <thead>
                  <tr style={{ background: "#FAF7F2", borderBottom: "1px solid #E6DCD2", color: "#5C544E" }}>
                    <th style={{ padding: "12px", textAlign: "left" }}>Timestamp Trigger</th>
                    <th style={{ padding: "12px", textAlign: "left" }}>Coupon Subject</th>
                    <th style={{ padding: "12px", textAlign: "left" }}>Action Signature</th>
                    <th style={{ padding: "12px", textAlign: "left" }}>User Scope Parameters</th>
                  </tr>
                </thead>
                <tbody>
                  {auditLogs.length === 0 ? (
                    <tr>
                      <td colSpan="4" style={{ padding: "20px", textAlign: "center", color: "#999" }}>No operational changes logged within active execution windows.</td>
                    </tr>
                  ) : (
                    auditLogs.map((log) => (
                      <tr key={log.id} style={{ borderBottom: "1px solid #FAF7F2" }}>
                        <td style={{ padding: "12px", color: "#5C544E" }}>
                          {log.timestamp?.seconds ? new Date(log.timestamp.seconds * 1000).toLocaleString() : "Real-time Processing"}
                        </td>
                        <td style={{ padding: "12px", fontWeight: "600", fontFamily: "monospace" }}>{log.code}</td>
                        <td style={{ padding: "12px" }}>
                          <span style={{ 
                            padding: "4px 8px", borderRadius: "4px", fontSize: "11px", fontWeight: "700",
                            background: log.action?.includes("CREATE") ? "#E8F5E9" : log.action?.includes("DELETE") ? "#FFEBEE" : "#FFF3E0",
                            color: log.action?.includes("CREATE") ? "#2E7D32" : log.action?.includes("DELETE") ? "#C62828" : "#EF6C00"
                          }}>
                            {log.action}
                          </span>
                        </td>
                        <td style={{ padding: "12px", color: "#777" }}>{log.category ? `${log.category} | Trigger: ${log.trigger || "manual"}` : "System Config Mod"}</td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
