import { useState, useEffect } from "react";
import {
  collection,
  addDoc,
  getDocs,
  deleteDoc,
  updateDoc,
  doc,
  writeBatch,
  serverTimestamp,
} from "firebase/firestore";
import { db } from "../firebase";
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  ResponsiveContainer,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  BarChart,
  Bar,
} from "recharts";

export default function CouponsAdminPage({ setPage }) {
  const [coupons, setCoupons] = useState([]);
  const [orders, setOrders] = useState([]); 
  const [auditLogs, setAuditLogs] = useState([]); 
  const [sortBy, setSortBy] = useState("newest");
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(null);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");
  const [revenueTimeframe, setRevenueTimeframe] = useState("30days");

  // State managers for Bulk Selection Operations
  const [selectedCouponIds, setSelectedCouponIds] = useState([]);
  const [copiedCode, setCopiedCode] = useState(null);

  const [newCoupon, setNewCoupon] = useState({
    code: "",
    type: "percentage",
    category: "General",
    value: "",
    maxDiscount: "",
    minOrder: "",
    usageLimit: "",
    perUserLimit: 1,
    starts: "",
    expires: "",
    singleUse: false,
    active: true,
    audienceType: "all", 
    targetUserId: "",
    isAutoGenerated: false,
    triggerType: "manual" 
  });

  const [editCoupon, setEditCoupon] = useState({
    code: "",
    type: "percentage",
    value: "",
    maxDiscount: "",
    minOrder: "",
    category: "General",
    starts: "",
    expires: "",
    usageLimit: "",
    perUserLimit: 1,
    singleUse: false,
    audienceType: "all",
    targetUserId: "",
    triggerType: "manual"
  });

  // --- SAFE DATA REDUCERS (WITH FALLBACK PROTECTION) ---
  const safeCoupons = Array.isArray(coupons) ? coupons : [];
  const safeOrders = Array.isArray(orders) ? orders : [];
  const safeLogs = Array.isArray(auditLogs) ? auditLogs : [];

  const totalUses = safeCoupons.reduce((sum, c) => sum + (Number(c?.usageCount) || 0), 0);
  const totalPossibleUses = safeCoupons.reduce((sum, c) => sum + (Number(c?.usageLimit) || 0), 0);
  const redemptionRate = totalPossibleUses > 0 ? ((totalUses / totalPossibleUses) * 100).toFixed(1) : 0;
  const totalDiscount = safeCoupons.reduce((sum, c) => sum + (Number(c?.totalDiscountGiven) || 0), 0);
  const totalRevenue = safeCoupons.reduce((sum, c) => sum + (Number(c?.totalRevenue) || 0), 0);

  const mostUsed =
    safeCoupons.length > 0
      ? [...safeCoupons].sort((a, b) => (Number(b?.usageCount) || 0) - (Number(a?.usageCount) || 0))[0]
      : null;

  const couponTypes = ["General", "New User", "Festival", "Birthday", "Referral", "Loyalty"];

  const categoryData = couponTypes.map((type) => ({
    name: type,
    value: safeCoupons.filter((c) => (c?.category || "General") === type).length,
  }));

  const usageData = [...safeCoupons]
    .sort((a, b) => (Number(a?.createdAt?.seconds) || 0) - (Number(b?.createdAt?.seconds) || 0))
    .map((coupon) => ({
      name: coupon?.code || "UNNAMED",
      uses: Number(coupon?.usageCount) || 0,
    }));

  // --- REVENUE INTERVAL PROCESSOR ENGINE ---
  const salesTodayStats = safeOrders.reduce(
    (stats, order) => {
      const orderDate = order?.createdAt?.seconds ? new Date(order.createdAt.seconds * 1000) : null;
      if (orderDate) {
        const today = new Date();
        if (
          orderDate.getDate() === today.getDate() &&
          orderDate.getMonth() === today.getMonth() &&
          orderDate.getFullYear() === today.getFullYear()
        ) {
          stats.count += 1;
          stats.revenue += Number(order?.totalPrice || 0);
        }
      }
      return stats;
    },
    { count: 0, revenue: 0 }
  );

  const getFilteredRevenueData = () => {
    const now = new Date();
    let cutoffLimitMs = 30 * 24 * 60 * 60 * 1000;
    let groupingKey = "date";

    if (revenueTimeframe === "14days") cutoffLimitMs = 14 * 24 * 60 * 60 * 1000;
    else if (revenueTimeframe === "7days") cutoffLimitMs = 7 * 24 * 60 * 60 * 1000;
    else if (revenueTimeframe === "3days") cutoffLimitMs = 3 * 24 * 60 * 60 * 1000;
    else if (revenueTimeframe === "48hrs") { cutoffLimitMs = 48 * 60 * 60 * 1000; groupingKey = "hour"; }
    else if (revenueTimeframe === "24hrs") { cutoffLimitMs = 24 * 60 * 60 * 1000; groupingKey = "hour"; }

    const cutoffDate = new Date(now.getTime() - cutoffLimitMs);
    const filtered = safeOrders.filter((o) => {
      const oDate = o?.createdAt?.seconds ? new Date(o.createdAt.seconds * 1000) : null;
      return oDate && oDate >= cutoffDate;
    });

    const aggregations = {};
    filtered.forEach((order) => {
      if (!order?.createdAt?.seconds) return;
      const oDate = new Date(order.createdAt.seconds * 1000);
      const key = groupingKey === "date" 
        ? oDate.toLocaleDateString(undefined, { month: "short", day: "numeric" })
        : `${oDate.getHours()}:00`;
      aggregations[key] = (aggregations[key] || 0) + Number(order?.totalPrice || 0);
    });

    return Object.keys(aggregations).map((key) => ({ label: key, amount: aggregations[key] }));
  };

  const revenueDataTimeline = getFilteredRevenueData();
  const totalSalesRevenueCollection = safeOrders.reduce((sum, o) => sum + Number(o?.totalPrice || 0), 0);

  // --- AUTOMATIC ALPHANUMERIC STRING ENGINE GENERATOR ---
  function handleGenerateRandomCode() {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    let token = "";
    for (let i = 0; i < 8; i++) {
      token += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    const prefix = (newCoupon.category || "GEN").substring(0, 3).toUpperCase();
    setNewCoupon({ ...newCoupon, code: `${prefix}-${token}`, isAutoGenerated: true });
  }

  // --- ONE-CLICK CLIPBOARD COPY MODULE ---
  function copyToClipboard(code) {
    if (!code) return;
    navigator.clipboard.writeText(code);
    setCopiedCode(code);
    setTimeout(() => setCopiedCode(null), 2000);
  }

  // --- CSV RAW STREAM EXPORTER MODULE ---
  function handleExportToCSV() {
    if (safeCoupons.length === 0) return alert("Repository empty. Aborting extraction.");
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Code,Category,Type,Value,Min Order,Usage Count,Usage Limit,Status,Expires\n";
    
    safeCoupons.forEach((c) => {
      csvContent += `${c.code || ""},${c.category || "General"},${c.type || ""},${c.value || 0},${c.minOrder || 0},${c.usageCount || 0},${c.usageLimit || "Unlimited"},${c.active ? "Active" : "Disabled"},${c.expires || "Never"}\n`;
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `coupon_repository_export_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  // --- DATA WORKFLOW COMPILATION BACKEND ---
  async function loadCoupons() {
    try {
      const couponSnapshot = await getDocs(collection(db, "coupons"));
      setCoupons(couponSnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })));
    } catch (e) {
      console.error("Firestore loading coupons error:", e);
    }

    try {
      const orderSnapshot = await getDocs(collection(db, "orders"));
      setOrders(orderSnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })));
    } catch (e) {
      console.error("Firestore loading orders error:", e);
    }

    try {
      const logSnapshot = await getDocs(collection(db, "coupon_audit_logs"));
      setAuditLogs(logSnapshot.docs.map(d => ({ id: d.id, ...d.data() })).sort((a,b) => (b.timestamp?.seconds || 0) - (a.timestamp?.seconds || 0)));
    } catch (e) {
      setAuditLogs([]);
    }
    
    setLoading(false);
  }

  useEffect(() => {
    loadCoupons();
  }, []);

  async function createAuditEntry(actionType, couponCode, metadata = {}) {
    try {
      await addDoc(collection(db, "coupon_audit_logs"), {
        action: actionType,
        code: couponCode,
        timestamp: new Date(),
        user: "Admin Operator",
        ...metadata
      });
    } catch (e) {
      console.error(e);
    }
  }

  // --- MULTI-SELECT BULK TRANSACTION METHODS ---
  async function handleBulkActivationToggle(targetStatus) {
    if (selectedCouponIds.length === 0) return alert("No documents selected.");
    if (!window.confirm(`Apply bulk status update across ${selectedCouponIds.length} items?`)) return;
    
    setLoading(true);
    try {
      const batch = writeBatch(db);
      selectedCouponIds.forEach((id) => {
        const docRef = doc(db, "coupons", id);
        batch.update(docRef, { active: targetStatus });
      });
      await batch.commit();
      await createAuditEntry("BULK_STATUS_MUTATION", `${selectedCouponIds.length} items`, { state: targetStatus });
    } catch (e) {
      alert("Error handling batch update. Check security rules.");
    }
    setSelectedCouponIds([]);
    await loadCoupons();
  }

  async function handleBulkPurge() {
    if (selectedCouponIds.length === 0) return alert("No documents selected.");
    if (!window.confirm(`⚠️ CRITICAL OPERATION: Permanently delete ${selectedCouponIds.length} selected items?`)) return;

    setLoading(true);
    try {
      const batch = writeBatch(db);
      selectedCouponIds.forEach((id) => {
        const docRef = doc(db, "coupons", id);
        batch.delete(docRef);
      });
      await batch.commit();
      await createAuditEntry("BULK_PURGE_EXECUTION", `${selectedCouponIds.length} items`);
    } catch (e) {
      alert("Error executing bulk delete.");
    }
    setSelectedCouponIds([]);
    await loadCoupons();
  }

  function toggleSelectCoupon(id) {
    if (selectedCouponIds.includes(id)) {
      setSelectedCouponIds(selectedCouponIds.filter(item => item !== id));
    } else {
      setSelectedCouponIds([...selectedCouponIds, id]);
    }
  }

  async function addCoupon() {
    if (!newCoupon.code || !newCoupon.value || !newCoupon.minOrder) {
      alert("Please complete all required fields.");
      return;
    }

    const payload = {
      code: newCoupon.code.toUpperCase(),
      type: newCoupon.type,
      category: newCoupon.category,
      value: Number(newCoupon.value),
      maxDiscount: Number(newCoupon.maxDiscount || 0),
      minOrder: Number(newCoupon.minOrder),
      active: newCoupon.active,
      usageLimit: Number(newCoupon.usageLimit || 0),
      usageCount: 0,
      starts: newCoupon.starts,
      expires: newCoupon.expires,
      singleUse: newCoupon.singleUse,
      perUserLimit: Number(newCoupon.perUserLimit),
      audienceType: newCoupon.audienceType,
      targetUserId: newCoupon.audienceType === "specific_user" ? newCoupon.targetUserId : "",
      triggerType: newCoupon.triggerType,
      createdAt: serverTimestamp(),
    };

    await addDoc(collection(db, "coupons"), payload);
    await createAuditEntry("CREATE_CAMPAIGN", payload.code, { category: payload.category });

    setNewCoupon({
      code: "", type: "percentage", category: "General", value: "", maxDiscount: "", minOrder: "",
      usageLimit: "", starts: "", expires: "", singleUse: false, perUserLimit: 1, active: true,
      audienceType: "all", targetUserId: "", isAutoGenerated: false, triggerType: "manual"
    });

    loadCoupons();
    alert("Coupon created successfully!");
  }

  async function deleteCoupon(id) {
    if (!window.confirm("Delete this coupon?")) return;
    const historicalDoc = safeCoupons.find(c => c.id === id);
    await deleteDoc(doc(db, "coupons", id));
    if (historicalDoc) await createAuditEntry("DELETE_CAMPAIGN", historicalDoc.code);
    loadCoupons();
  }

  async function toggleCoupon(coupon) {
    const nextState = !coupon.active;
    await updateDoc(doc(db, "coupons", coupon.id), { active: nextState });
    await createAuditEntry(nextState ? "ENABLE_CAMPAIGN" : "DISABLE_CAMPAIGN", coupon.code);
    loadCoupons();
  }

  async function updateCoupon() {
    if (!editing) return;

    await updateDoc(doc(db, "coupons", editing.id), {
      code: editCoupon.code.toUpperCase(),
      type: editCoupon.type,
      value: Number(editCoupon.value),
      maxDiscount: Number(editCoupon.maxDiscount),
      minOrder: Number(editCoupon.minOrder),
      category: editCoupon.category,
      starts: editCoupon.starts,
      expires: editCoupon.expires,
      usageLimit: Number(editCoupon.usageLimit),
      perUserLimit: Number(editCoupon.perUserLimit),
      singleUse: editCoupon.singleUse,
      audienceType: editCoupon.audienceType,
      targetUserId: editCoupon.audienceType === "specific_user" ? editCoupon.targetUserId : "",
      triggerType: editCoupon.triggerType
    });

    await createAuditEntry("UPDATE_METADATA", editCoupon.code.toUpperCase());
    alert("Coupon updated!");
    setEditing(null);
    loadCoupons();
  }

  // --- STAT CARDS WORKSPACE RENDERS ---
  function StatCard({ title, value, color, icon, highlight }) {
    return (
      <div
        style={{
          background: highlight ? "linear-gradient(135deg, #1E1B18 0%, #3B342E 100%)" : "#fff",
          padding: "25px",
          borderRadius: "16px",
          boxShadow: "0 10px 30px rgba(196,149,106,0.06)",
          border: "1px solid rgba(230, 220, 210, 0.4)",
          display: "flex",
          alignItems: "center",
          gap: "20px",
        }}
      >
        <div style={{ fontSize: "30px", background: highlight ? "rgba(255,255,255,0.08)" : `${color}10`, padding: "14px", borderRadius: "14px", display: "flex", alignItems: "center" }}>
          {icon}
        </div>
        <div>
          <p style={{ color: highlight ? "#C4956A" : "#8A827C", margin: 0, fontSize: "12px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.5px" }}>{title}</p>
          <h1 style={{ marginTop: "4px", marginBottom: 0, color: highlight ? "#fff" : "#1E1B18", fontSize: "26px", fontWeight: "700", fontFamily: "monospace" }}>{value}</h1>
        </div>
      </div>
    );
  }

  function getCategoryColor(category) {
    switch (category) {
      case "New User": return { bg: "#E3F2FD", border: "#90CAF9", color: "#0D47A1", cardBg: "#F7FAFC" };
      case "Festival": return { bg: "#FFF3E0", border: "#FFB74D", color: "#E65100", cardBg: "#FFFDF9" };
      case "Birthday": return { bg: "#FCE4EC", border: "#F48FB1", color: "#880E4F", cardBg: "#FFF9FA" };
      case "Referral": return { bg: "#E8F5E9", border: "#A5D6A7", color: "#1B5E20", cardBg: "#FAFEFA" };
      case "Loyalty": return { bg: "#F3E5F5", border: "#CE93D8", color: "#4A148C", cardBg: "#FCF9FC" };
      default: return { bg: "#ECEFF1", border: "#B0BEC5", color: "#263238", cardBg: "#FFFFFF" };
    }
  }

  function getExpiryStatus(expires, starts) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    if (starts) {
      const activationDate = new Date(starts);
      activationDate.setHours(0, 0, 0, 0);
      if (activationDate > today) {
        return { label: "⏳ Scheduled Activation", variant: "scheduled" };
      }
    }

    if (!expires) return { label: "♾️ Active Permanent", variant: "permanent" };
    const expiry = new Date(expires);
    expiry.setHours(0, 0, 0, 0);
    const days = Math.ceil((expiry - today) / (1000 * 60 * 60 * 24));
    
    if (days < 0) return { label: "🚨 Expired Past Limit", variant: "expired" };
    if (days <= 3) return { label: `⚠️ Expiring Soon (${days}d)`, variant: "warning" };
    return { label: `⏳ Valid (${days} days left)`, variant: "valid" };
  }

  const formInputStyle = {
    padding: "12px 16px",
    borderRadius: "10px",
    border: "1px solid #DCD1C4",
    width: "100%",
    boxSizing: "border-box",
    fontSize: "14px",
    background: "#FCFBFA",
    outline: "none",
    fontFamily: "inherit"
  };

  const COLORS = [
  "#C4956A",
  "#4F46E5",
  "#2E7D32",
  "#F59E0B",
  "#EC4899",
  "#06B6D4",
];

  // --- MASTER RENDER LAYER WITH CRASH SAFEGUARDS ---
  if (!db) {
    return <div style={{ padding: "50px", textAlign: "center", color: "red" }}>Error: Firebase db connection configuration missing in context resources.</div>;
  }

  return (
    <div style={{ minHeight: "100vh", background: "#FAF6F0", padding: "40px 4%", fontFamily: "system-ui, -apple-system, sans-serif" }}>
      
      {/* Dynamic Navigation Top Row */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "35px" }}>
        <div>
          <button onClick={() => setPage("admin")} style={{ background: "#fff", border: "1px solid #DCD1C4", padding: "10px 18px", borderRadius: "8px", cursor: "pointer", fontWeight: "600", color: "#544E48" }}>
            ← Back Dashboard
          </button>
          <h1 style={{ fontFamily: "Playfair Display, serif", marginTop: "16px", marginBottom: 0, fontSize: "34px", color: "#1E1B18" }}>
            🎟️ Master Coupon Control Center
          </h1>
        </div>
      </div>

      {/* CORE LIVE TRANSACTIONAL SALES HUD */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "20px", marginBottom: "40px" }}>
        <StatCard title="Sales Confirmed Today" value={`${salesTodayStats.count} Orders`} color="#fff" icon="🛍️" highlight={true} />
        <StatCard title="Revenue Captured Today" value={`₹${salesTodayStats.revenue}`} color="#009688" icon="⚡" />
        <StatCard title="All-Time Total Revenue" value={`₹${totalSalesRevenueCollection}`} color="#2E7D32" icon="💼" />
        <StatCard title="Active Templates" value={safeCoupons.filter(c => c?.active).length} color="#3B1A08" icon="⚙️" />
      </div>

      {/* VISUAL CHART REPORT FLEX LAYOUT BLOCKS */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(420px, 1fr))", gap: "25px", marginBottom: "40px" }}>
        
        {/* Dynamic Windowed Income Distribution Graph Block */}
        <div style={{ background: "#fff", borderRadius: "16px", padding: "24px", border: "1px solid #EAE1D4", boxShadow: "0 4px 20px rgba(0,0,0,0.01)" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
            <h3 style={{ margin: 0, fontSize: "16px", fontWeight: "700" }}>📊 Channel Income Processing Wave</h3>
            <select value={revenueTimeframe} onChange={(e) => setRevenueTimeframe(e.target.value)} style={{ padding: "8px 12px", borderRadius: "8px", border: "1px solid #DCD1C4", fontSize: "13px", fontWeight: "600" }}>
              <option value="30days">📅 Last 30 Days</option>
              <option value="14days">📅 Last 14 Days</option>
              <option value="7days">📅 Last 7 Days</option>
              <option value="3days">📆 Last 3 Days</option>
              <option value="48hrs">⏳ Last 48 Hours</option>
              <option value="24hrs">⏳ Last 24 Hours</option>
            </select>
          </div>
          <ResponsiveContainer width="100%" height={240}>
            {revenueDataTimeline.length > 0 ? (
              <BarChart data={revenueDataTimeline}>
                <CartesianGrid strokeDasharray="3 3" stroke="#FAF6F0" />
                <XAxis dataKey="label" stroke="#A8A096" style={{ fontSize: "11px" }} />
                <YAxis stroke="#A8A096" style={{ fontSize: "11px" }} />
                <Tooltip formatter={(v) => [`₹${v}`, "Captured Revenue"]} />
                <Bar dataKey="amount" fill="#3B1A08" radius={[4, 4, 0, 0]} />
              </BarChart>
            ) : (
              <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: "100%", color: "#A8A096" }}>Zero points parsed inside limits</div>
            )}
          </ResponsiveContainer>
        </div>

      
