import { useState, useEffect } from "react";
import {
  collection,
  addDoc,
  getDocs,
  deleteDoc,
  updateDoc,
  doc,
  writeBatch,
  serverTimestamp,
} from "firebase/firestore";
import { db } from "../firebase";
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  ResponsiveContainer,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  BarChart,
  Bar,
} from "recharts";

export default function CouponManagement({ setPage, setActivePage }) {
  const [coupons, setCoupons] = useState([]);
  const [orders, setOrders] = useState([]); 
  const [auditLogs, setAuditLogs] = useState([]); 
  const [sortBy, setSortBy] = useState("newest");
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(null);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");
  const [revenueTimeframe, setRevenueTimeframe] = useState("30days");

  // State managers for Bulk Selection Operations
  const [selectedCouponIds, setSelectedCouponIds] = useState([]);
  const [copiedCode, setCopiedCode] = useState(null);

  const [newCoupon, setNewCoupon] = useState({
    code: "",
    type: "percentage",
    category: "General",
    value: "",
    maxDiscount: "",
    minOrder: "",
    usageLimit: "",
    perUserLimit: 1,
    starts: "",
    expires: "",
    singleUse: false,
    active: true,
    audienceType: "all", 
    targetUserId: "",
    isAutoGenerated: false,
    triggerType: "manual" 
  });

  const [editCoupon, setEditCoupon] = useState({
    code: "",
    type: "percentage",
    value: "",
    maxDiscount: "",
    minOrder: "",
    category: "General",
    starts: "",
    expires: "",
    usageLimit: "",
    perUserLimit: 1,
    singleUse: false,
    audienceType: "all",
    targetUserId: "",
    triggerType: "manual"
  });

  // --- SAFE DATA REDUCERS (WITH FALLBACK PROTECTION) ---
  const safeCoupons = Array.isArray(coupons) ? coupons : [];
  const safeOrders = Array.isArray(orders) ? orders : [];
  const safeLogs = Array.isArray(auditLogs) ? auditLogs : [];

  const totalUses = safeCoupons.reduce((sum, c) => sum + (Number(c?.usageCount) || 0), 0);
  const totalPossibleUses = safeCoupons.reduce((sum, c) => sum + (Number(c?.usageLimit) || 0), 0);
  const redemptionRate = totalPossibleUses > 0 ? ((totalUses / totalPossibleUses) * 100).toFixed(1) : 0;
  const totalDiscount = safeCoupons.reduce((sum, c) => sum + (Number(c?.totalDiscountGiven) || 0), 0);
  const totalRevenue = safeCoupons.reduce((sum, c) => sum + (Number(c?.totalRevenue) || 0), 0);

  const mostUsed =
    safeCoupons.length > 0
      ? [...safeCoupons].sort((a, b) => (Number(b?.usageCount) || 0) - (Number(a?.usageCount) || 0))[0]
      : null;

  const couponTypes = ["General", "New User", "Festival", "Birthday", "Referral", "Loyalty"];

  const categoryData = couponTypes.map((type) => ({
    name: type,
    value: safeCoupons.filter((c) => (c?.category || "General") === type).length,
  }));

  const usageData = [...safeCoupons]
    .sort((a, b) => (Number(a?.createdAt?.seconds) || 0) - (Number(b?.createdAt?.seconds) || 0))
    .map((coupon) => ({
      name: coupon?.code || "UNNAMED",
      uses: Number(coupon?.usageCount) || 0,
    }));

  // --- REVENUE INTERVAL PROCESSOR ENGINE ---
  const salesTodayStats = safeOrders.reduce(
    (stats, order) => {
      const orderDate = order?.createdAt?.seconds ? new Date(order.createdAt.seconds * 1000) : null;
      if (orderDate) {
        const today = new Date();
        if (
          orderDate.getDate() === today.getDate() &&
          orderDate.getMonth() === today.getMonth() &&
          orderDate.getFullYear() === today.getFullYear()
        ) {
          stats.count += 1;
          stats.revenue += Number(order?.totalPrice || 0);
        }
      }
      return stats;
    },
    { count: 0, revenue: 0 }
  );

  const getFilteredRevenueData = () => {
    const now = new Date();
    let cutoffLimitMs = 30 * 24 * 60 * 60 * 1000;
    let groupingKey = "date";

    if (revenueTimeframe === "14days") cutoffLimitMs = 14 * 24 * 60 * 60 * 1000;
    else if (revenueTimeframe === "7days") cutoffLimitMs = 7 * 24 * 60 * 60 * 1000;
    else if (revenueTimeframe === "3days") cutoffLimitMs = 3 * 24 * 60 * 60 * 1000;
    else if (revenueTimeframe === "48hrs") { cutoffLimitMs = 48 * 60 * 60 * 1000; groupingKey = "hour"; }
    else if (revenueTimeframe === "24hrs") { cutoffLimitMs = 24 * 60 * 60 * 1000; groupingKey = "hour"; }

    const cutoffDate = new Date(now.getTime() - cutoffLimitMs);
    const filtered = safeOrders.filter((o) => {
      const oDate = o?.createdAt?.seconds ? new Date(o.createdAt.seconds * 1000) : null;
      return oDate && oDate >= cutoffDate;
    });

    const aggregations = {};
    filtered.forEach((order) => {
      if (!order?.createdAt?.seconds) return;
      const oDate = new Date(order.createdAt.seconds * 1000);
      const key = groupingKey === "date" 
        ? oDate.toLocaleDateString(undefined, { month: "short", day: "numeric" })
        : `${oDate.getHours()}:00`;
      aggregations[key] = (aggregations[key] || 0) + Number(order?.totalPrice || 0);
    });

    return Object.keys(aggregations).map((key) => ({ label: key, amount: aggregations[key] }));
  };

  const revenueDataTimeline = getFilteredRevenueData();
  const totalSalesRevenueCollection = safeOrders.reduce((sum, o) => sum + Number(o?.totalPrice || 0), 0);

  // --- AUTOMATIC ALPHANUMERIC STRING ENGINE GENERATOR ---
  function handleGenerateRandomCode() {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    let token = "";
    for (let i = 0; i < 8; i++) {
      token += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    const prefix = (newCoupon.category || "GEN").substring(0, 3).toUpperCase();
    setNewCoupon({ ...newCoupon, code: `${prefix}-${token}`, isAutoGenerated: true });
  }

  // --- ONE-CLICK CLIPBOARD COPY MODULE ---
  function copyToClipboard(code) {
    if (!code) return;
    navigator.clipboard.writeText(code);
    setCopiedCode(code);
    setTimeout(() => setCopiedCode(null), 2000);
  }

  // --- CSV RAW STREAM EXPORTER MODULE ---
  function handleExportToCSV() {
    if (safeCoupons.length === 0) return alert("Repository empty. Aborting extraction.");
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Code,Category,Type,Value,Min Order,Usage Count,Usage Limit,Status,Expires\n";
    
    safeCoupons.forEach((c) => {
      csvContent += `${c.code || ""},${c.category || "General"},${c.type || ""},${c.value || 0},${c.minOrder || 0},${c.usageCount || 0},${c.usageLimit || "Unlimited"},${c.active ? "Active" : "Disabled"},${c.expires || "Never"}\n`;
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `coupon_repository_export_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  // --- DATA WORKFLOW COMPILATION BACKEND ---
  async function loadCoupons() {
    try {
      const couponSnapshot = await getDocs(collection(db, "coupons"));
      setCoupons(couponSnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })));
    } catch (e) {
      console.error("Firestore loading coupons error:", e);
    }

    try {
      const orderSnapshot = await getDocs(collection(db, "orders"));
      setOrders(orderSnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })));
    } catch (e) {
      console.error("Firestore loading orders error:", e);
    }

    try {
      const logSnapshot = await getDocs(collection(db, "coupon_audit_logs"));
      setAuditLogs(logSnapshot.docs.map(d => ({ id: d.id, ...d.data() })).sort((a,b) => (b.timestamp?.seconds || 0) - (a.timestamp?.seconds || 0)));
    } catch (e) {
      setAuditLogs([]);
    }
    
    setLoading(false);
  }

  useEffect(() => {
    loadCoupons();
  }, []);

  async function createAuditEntry(actionType, couponCode, metadata = {}) {
    try {
      await addDoc(collection(db, "coupon_audit_logs"), {
        action: actionType,
        code: couponCode,
        timestamp: new Date(),
        user: "Admin Operator",
        ...metadata
      });
    } catch (e) {
      console.error(e);
    }
  }

  // --- MULTI-SELECT BULK TRANSACTION METHODS ---
  async function handleBulkActivationToggle(targetStatus) {
    if (selectedCouponIds.length === 0) return alert("No documents selected.");
    if (!window.confirm(`Apply bulk status update across ${selectedCouponIds.length} items?`)) return;
    
    setLoading(true);
    try {
      const batch = writeBatch(db);
      selectedCouponIds.forEach((id) => {
        const docRef = doc(db, "coupons", id);
        batch.update(docRef, { active: targetStatus });
      });
      await batch.commit();
      await createAuditEntry("BULK_STATUS_MUTATION", `${selectedCouponIds.length} items`, { state: targetStatus });
    } catch (e) {
      alert("Error handling batch update. Check security rules.");
    }
    setSelectedCouponIds([]);
    await loadCoupons();
  }

  async function handleBulkPurge() {
    if (selectedCouponIds.length === 0) return alert("No documents selected.");
    if (!window.confirm(`⚠️ CRITICAL OPERATION: Permanently delete ${selectedCouponIds.length} selected items?`)) return;

    setLoading(true);
    try {
      const batch = writeBatch(db);
      selectedCouponIds.forEach((id) => {
        const docRef = doc(db, "coupons", id);
        batch.delete(docRef);
      });
      await batch.commit();
      await createAuditEntry("BULK_PURGE_EXECUTION", `${selectedCouponIds.length} items`);
    } catch (e) {
      alert("Error executing bulk delete.");
    }
    setSelectedCouponIds([]);
    await loadCoupons();
  }

  function toggleSelectCoupon(id) {
    if (selectedCouponIds.includes(id)) {
      setSelectedCouponIds(selectedCouponIds.filter(item => item !== id));
    } else {
      setSelectedCouponIds([...selectedCouponIds, id]);
    }
  }

  async function addCoupon() {
    if (!newCoupon.code || !newCoupon.value || !newCoupon.minOrder) {
      alert("Please complete all required fields.");
      return;
    }

    const payload = {
      code: newCoupon.code.toUpperCase(),
      type: newCoupon.type,
      category: newCoupon.category,
      value: Number(newCoupon.value),
      maxDiscount: Number(newCoupon.maxDiscount || 0),
      minOrder: Number(newCoupon.minOrder),
      active: newCoupon.active,
      usageLimit: Number(newCoupon.usageLimit || 0),
      usageCount: 0,
      starts: newCoupon.starts,
      expires: newCoupon.expires,
      singleUse: newCoupon.singleUse,
      perUserLimit: Number(newCoupon.perUserLimit),
      audienceType: newCoupon.audienceType,
      targetUserId: newCoupon.audienceType === "specific_user" ? newCoupon.targetUserId : "",
      triggerType: newCoupon.triggerType,
      createdAt: serverTimestamp(),
    };

    await addDoc(collection(db, "coupons"), payload);
    await createAuditEntry("CREATE_CAMPAIGN", payload.code, { category: payload.category });

    setNewCoupon({
      code: "", type: "percentage", category: "General", value: "", maxDiscount: "", minOrder: "",
      usageLimit: "", starts: "", expires: "", singleUse: false, perUserLimit: 1, active: true,
      audienceType: "all", targetUserId: "", isAutoGenerated: false, triggerType: "manual"
    });

    loadCoupons();
    alert("Coupon created successfully!");
  }

  async function deleteCoupon(id) {
    if (!window.confirm("Delete this coupon?")) return;
    const historicalDoc = safeCoupons.find(c => c.id === id);
    await deleteDoc(doc(db, "coupons", id));
    if (historicalDoc) await createAuditEntry("DELETE_CAMPAIGN", historicalDoc.code);
    loadCoupons();
  }

  async function toggleCoupon(coupon) {
    const nextState = !coupon.active;
    await updateDoc(doc(db, "coupons", coupon.id), { active: nextState });
    await createAuditEntry(nextState ? "ENABLE_CAMPAIGN" : "DISABLE_CAMPAIGN", coupon.code);
    loadCoupons();
  }

  async function updateCoupon() {
    if (!editing) return;

    await updateDoc(doc(db, "coupons", editing.id), {
      code: editCoupon.code.toUpperCase(),
      type: editCoupon.type,
      value: Number(editCoupon.value),
      maxDiscount: Number(editCoupon.maxDiscount),
      minOrder: Number(editCoupon.minOrder),
      category: editCoupon.category,
      starts: editCoupon.starts,
      expires: editCoupon.expires,
      usageLimit: Number(editCoupon.usageLimit),
      perUserLimit: Number(editCoupon.perUserLimit),
      singleUse: editCoupon.singleUse,
      audienceType: editCoupon.audienceType,
      targetUserId: editCoupon.audienceType === "specific_user" ? editCoupon.targetUserId : "",
      triggerType: editCoupon.triggerType
    });

    await createAuditEntry("UPDATE_METADATA", editCoupon.code.toUpperCase());
    alert("Coupon updated!");
    setEditing(null);
    loadCoupons();
  }

  // --- STAT CARDS WORKSPACE RENDERS ---
  function StatCard({ title, value, color, icon, highlight }) {
    return (
      <div
        style={{
          background: highlight ? "linear-gradient(135deg, #1E1B18 0%, #3B342E 100%)" : "#fff",
          padding: "25px",
          borderRadius: "16px",
          boxShadow: "0 10px 30px rgba(196,149,106,0.06)",
          border: "1px solid rgba(230, 220, 210, 0.4)",
          display: "flex",
          alignItems: "center",
          gap: "20px",
        }}
      >
        <div style={{ fontSize: "30px", background: highlight ? "rgba(255,255,255,0.08)" : `${color}10`, padding: "14px", borderRadius: "14px", display: "flex", alignItems: "center" }}>
          {icon}
        </div>
        <div>
          <p style={{ color: highlight ? "#C4956A" : "#8A827C", margin: 0, fontSize: "12px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.5px" }}>{title}</p>
          <h1 style={{ marginTop: "4px", marginBottom: 0, color: highlight ? "#fff" : "#1E1B18", fontSize: "26px", fontWeight: "700", fontFamily: "monospace" }}>{value}</h1>
        </div>
      </div>
    );
  }

  function getCategoryColor(category) {
    switch (category) {
      case "New User": return { bg: "#E3F2FD", border: "#90CAF9", color: "#0D47A1", cardBg: "#F7FAFC" };
      case "Festival": return { bg: "#FFF3E0", border: "#FFB74D", color: "#E65100", cardBg: "#FFFDF9" };
      case "Birthday": return { bg: "#FCE4EC", border: "#F48FB1", color: "#880E4F", cardBg: "#FFF9FA" };
      case "Referral": return { bg: "#E8F5E9", border: "#A5D6A7", color: "#1B5E20", cardBg: "#FAFEFA" };
      case "Loyalty": return { bg: "#F3E5F5", border: "#CE93D8", color: "#4A148C", cardBg: "#FCF9FC" };
      default: return { bg: "#ECEFF1", border: "#B0BEC5", color: "#263238", cardBg: "#FFFFFF" };
    }
  }

  function getExpiryStatus(expires, starts) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    if (starts) {
      const activationDate = new Date(starts);
      activationDate.setHours(0, 0, 0, 0);
      if (activationDate > today) {
        return { label: "⏳ Scheduled Activation", variant: "scheduled" };
      }
    }

    if (!expires) return { label: "♾️ Active Permanent", variant: "permanent" };
    const expiry = new Date(expires);
    expiry.setHours(0, 0, 0, 0);
    const days = Math.ceil((expiry - today) / (1000 * 60 * 60 * 24));
    
    if (days < 0) return { label: "🚨 Expired Past Limit", variant: "expired" };
    if (days <= 3) return { label: `⚠️ Expiring Soon (${days}d)`, variant: "warning" };
    return { label: `⏳ Valid (${days} days left)`, variant: "valid" };
  }

  const formInputStyle = {
    padding: "12px 16px",
    borderRadius: "10px",
    border: "1px solid #DCD1C4",
    width: "100%",
    boxSizing: "border-box",
    fontSize: "14px",
    background: "#FCFBFA",
    outline: "none",
    fontFamily: "inherit"
  };

  const COLORS = [
  "#C4956A",
  "#4F46E5",
  "#2E7D32",
  "#F59E0B",
  "#EC4899",
  "#06B6D4",
];

  // --- MASTER RENDER LAYER WITH CRASH SAFEGUARDS ---
  if (!db) {
    return <div style={{ padding: "50px", textAlign: "center", color: "red" }}>Error: Firebase db connection configuration missing in context resources.</div>;
  }

  return (
    <div style={{ minHeight: "100vh", background: "#FAF6F0", padding: "40px 4%", fontFamily: "system-ui, -apple-system, sans-serif" }}>
      
      {/* Dynamic Navigation Top Row */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "35px" }}>
        <div>
          <button onClick={() => setPage("admin")} style={{ background: "#fff", border: "1px solid #DCD1C4", padding: "10px 18px", borderRadius: "8px", cursor: "pointer", fontWeight: "600", color: "#544E48" }}>
            ← Back Dashboard
          </button>
          <h1 style={{ fontFamily: "Playfair Display, serif", marginTop: "16px", marginBottom: 0, fontSize: "34px", color: "#1E1B18" }}>
            🎟️ Master Coupon Control Center
          </h1>
        </div>
      </div>

      {/* CORE LIVE TRANSACTIONAL SALES HUD */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "20px", marginBottom: "40px" }}>
        <StatCard title="Sales Confirmed Today" value={`${salesTodayStats.count} Orders`} color="#fff" icon="🛍️" highlight={true} />
        <StatCard title="Revenue Captured Today" value={`₹${salesTodayStats.revenue}`} color="#009688" icon="⚡" />
        <StatCard title="All-Time Total Revenue" value={`₹${totalSalesRevenueCollection}`} color="#2E7D32" icon="💼" />
        <StatCard title="Active Templates" value={safeCoupons.filter(c => c?.active).length} color="#3B1A08" icon="⚙️" />
      </div>

      {/* VISUAL CHART REPORT FLEX LAYOUT BLOCKS */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(420px, 1fr))", gap: "25px", marginBottom: "40px" }}>
        
        {/* Dynamic Windowed Income Distribution Graph Block */}
        <div style={{ background: "#fff", borderRadius: "16px", padding: "24px", border: "1px solid #EAE1D4", boxShadow: "0 4px 20px rgba(0,0,0,0.01)" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
            <h3 style={{ margin: 0, fontSize: "16px", fontWeight: "700" }}>📊 Channel Income Processing Wave</h3>
            <select value={revenueTimeframe} onChange={(e) => setRevenueTimeframe(e.target.value)} style={{ padding: "8px 12px", borderRadius: "8px", border: "1px solid #DCD1C4", fontSize: "13px", fontWeight: "600" }}>
              <option value="30days">📅 Last 30 Days</option>
              <option value="14days">📅 Last 14 Days</option>
              <option value="7days">📅 Last 7 Days</option>
              <option value="3days">📆 Last 3 Days</option>
              <option value="48hrs">⏳ Last 48 Hours</option>
              <option value="24hrs">⏳ Last 24 Hours</option>
            </select>
          </div>
          <ResponsiveContainer width="100%" height={240}>
            {revenueDataTimeline.length > 0 ? (
              <BarChart data={revenueDataTimeline}>
                <CartesianGrid strokeDasharray="3 3" stroke="#FAF6F0" />
                <XAxis dataKey="label" stroke="#A8A096" style={{ fontSize: "11px" }} />
                <YAxis stroke="#A8A096" style={{ fontSize: "11px" }} />
                <Tooltip formatter={(v) => [`₹${v}`, "Captured Revenue"]} />
                <Bar dataKey="amount" fill="#3B1A08" radius={[4, 4, 0, 0]} />
              </BarChart>
            ) : (
              <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: "100%", color: "#A8A096" }}>Zero points parsed inside limits</div>
            )}
          </ResponsiveContainer>
        </div>

        {/* Categories Pie Mixer Layout Block */}
        <div style={{ background: "#fff", borderRadius: "16px", padding: "24px", border: "1px solid #EAE1D4", boxShadow: "0 4px 20px rgba(0,0,0,0.01)" }}>
          <h3 style={{ margin: "0 0 20px 0", fontSize: "16px", fontWeight: "700" }}>🥧 Dynamic Structural Mix Ratios</h3>
          <ResponsiveContainer width="100%" height={240}>
            <PieChart>
              <Pie data={categoryData} dataKey="value" nameKey="name" outerRadius={75} innerRadius={50} paddingAngle={4}>
                {categoryData.map((entry, index) => <Cell key={index} fill={COLORS[index % COLORS.length]} />)}
              </Pie>
              <Tooltip />
              <Legend wrapperStyle={{ fontSize: "12px" }} />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* EXTENDED RETROACTIVE MATRIX GRID SUMMARY */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: "20px", marginBottom: "40px" }}>
        <StatCard title="Total Repository" value={safeCoupons.length} color="#3B1A08" icon="📋" />
        <StatCard title="Total Redemptions" value={totalUses} color="#C4956A" icon="🔥" />
        <StatCard title="Discounts Distributed" value={`₹${totalDiscount}`} color="#4F46E5" icon="💸" />
        <StatCard title="System Efficiency" value={`${redemptionRate}%`} color="#FF9800" icon="📈" />
        <StatCard title="Linked Asset Val" value={`₹${totalRevenue}`} color="#009688" icon="💰" />
      </div>

      {/* WORKSPACE COLUMN SPLIT ROUTER CONTAINER */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(350px, 1fr))", gap: "30px", alignItems: "start" }}>
        
        {/* WORKSPACE FORM PANELS INTERACTIVE CONTROL SHEET */}
        <div style={{ display: "flex", flexDirection: "column", gap: "35px" }}>
          
          {/* COMPLETE FORM WORKSPACE MATRIX */}
          <div style={{ background: "#fff", borderRadius: "16px", padding: "28px", border: "1px solid #EAE1D4", boxShadow: "0 4px 25px rgba(0,0,0,0.02)" }}>
            <h2 style={{ fontFamily: "Playfair Display, serif", margin: "0 0 24px 0", fontSize: "22px" }}>✨ Deploy System Engine Parameter</h2>
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              
              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Category Core Logic Class</label>
                <select style={formInputStyle} value={newCoupon.category} onChange={(e) => setNewCoupon({ ...newCoupon, category: e.target.value })}>
                  <option value="General">🏷️ General Release Template</option>
                  <option value="New User">👤 First-Order / New User Trigger</option>
                  <option value="Festival">🎉 Seasonal Festival Allocation</option>
                  <option value="Birthday">🎂 Automated Birthday Sequence</option>
                  <option value="Referral">🤝 Dynamic Referral Bonus Reward</option>
                  <option value="Loyalty">💎 Milestone Loyalty Protocol</option>
                </select>
              </div>

              <div>
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "6px" }}>
                  <label style={{ fontSize: "13px", fontWeight: "600" }}>Unique Code Alphanumeric Token *</label>
                  <span onClick={handleGenerateRandomCode} style={{ fontSize: "12px", color: "#4F46E5", cursor: "pointer", fontWeight: "600" }}>⚙️ Engine Auto-Gen</span>
                </div>
                <input style={formInputStyle} placeholder="SUMMER50" value={newCoupon.code} onChange={(e) => setNewCoupon({ ...newCoupon, code: e.target.value.toUpperCase(), isAutoGenerated: false })} />
              </div>

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Audience Filter Pipeline</label>
                <select style={formInputStyle} value={newCoupon.audienceType} onChange={(e) => setNewCoupon({ ...newCoupon, audienceType: e.target.value })}>
                  <option value="all">🌐 Open Public Ecosystem</option>
                  <option value="new_users_only">🆕 First-Order Accounts Only</option>
                  <option value="specific_user">👤 Customer-Specific (Explicit Target Mapping)</option>
                </select>
              </div>

              {newCoupon.audienceType === "specific_user" && (
                <div>
                  <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>Target Account Unique ID Constraint *</label>
                  <input style={formInputStyle} placeholder="usr_x28a31b" value={newCoupon.targetUserId} onChange={(e) => setNewCoupon({ ...newCoupon, targetUserId: e.target.value })} />
                </div>
              )}

              <div>
                <label style={{ display: "block", fontSize: "13px", fontWeight: "600", marginBottom: "6px" }}>System Automation Trigger Integration</label>
                <select style={formInputStyle} value={newCoupon.triggerType} onChange={(e) => setNewCoupon({ ...newCoupon, triggerType: e.target.value })}>
                  <option value="manual">Manual Direct Assignment</option>
                  <option value="birthday_event">🎂 Auto-Generate on Profile Birthday Matches</option>
                  <option value="referral_generation">🤝 Auto-Generate via Affiliate Tracker Hook</option>
                </select>
              </div>

              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
                <div>
                  <label style={{ display: "block", fontSize: "12px", fontWeight: "600", marginBottom: "4px" }}>Discount Structure</label>
                  <select style={formInputStyle} value={newCoupon.type} onChange={(e) => setNewCoupon({ ...newCoupon, type: e.target.value })}>
                    <option value="percentage">Percentage (%)</option>
                    <option value="fixed">Fixed Flat (₹)</option>
                  </select>
                </div>
                <div>
                  <label style={{ display: "block", fontSize: "12px", fontWeight: "600", marginBottom: "4px" }}>Rate Value *</label>
                  <input type="number" style={formInputStyle} value={newCoupon.value} onChange={(e) => setNewCoupon({ ...newCoupon, value: e.target.value })} />
                </div>
              </div>

              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
                <div>
                  <label style={{ display: "block", fontSize: "12px", fontWeight: "600", marginBottom: "4px" }}>Order Constraint (₹) *</label>
                  <input type="number" style={formInputStyle} value={newCoupon.minOrder} onChange={(e) => setNewCoupon({ ...newCoupon, minOrder: e.target.value })} />
                </div>
                <div>
                  <label style={{ display: "block", fontSize: "12px", fontWeight: "600", marginBottom: "4px" }}>Max Discount Cap (₹)</label>
                  <input type="number" style={formInputStyle} value={newCoupon.maxDiscount} onChange={(e) => setNewCoupon({ ...newCoupon, maxDiscount: e.target.value })} />
                </div>
              </div>

              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
                <div>
                  <label style={{ display: "block", fontSize: "12px", fontWeight: "600", marginBottom: "4px" }}>Global Cap Threshold</label>
                  <input type="number" style={formInputStyle} value={newCoupon.usageLimit} onChange={(e) => setNewCoupon({ ...newCoupon, usageLimit: e.target.value })} />
                </div>
                <div>
                  <label style={{ display: "block", fontSize: "12px", fontWeight: "600", marginBottom: "4px" }}>Per-User Limit Cap</label>
                  <input type="number" style={formInputStyle} value={newCoupon.perUserLimit} onChange={(e) => setNewCoupon({ ...newCoupon, perUserLimit: e.target.value })} />
                </div>
              </div>

              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
                <div>
                  <label style={{ display: "block", fontSize: "12px", fontWeight: "600", marginBottom: "4px" }}>Scheduled Activation</label>
                  <input type="date" style={formInputStyle} value={newCoupon.starts} onChange={(e) => setNewCoupon({ ...newCoupon, starts: e.target.value })} />
                </div>
                <div>
                  <label style={{ display: "block", fontSize: "12px", fontWeight: "600", marginBottom: "4px" }}>Horizon Expiry</label>
                  <input type="date" style={formInputStyle} value={newCoupon.expires} onChange={(e) => setNewCoupon({ ...newCoupon, expires: e.target.value })} />
                </div>
              </div>

              <div>
                <label style={{ display: "block", fontSize: "12px", fontWeight: "600", marginBottom: "4px" }}>Allocation Mode</label>
                <select style={formInputStyle} value={newCoupon.singleUse ? "single" : "multi"} onChange={(e) => setNewCoupon({ ...newCoupon, singleUse: e.target.value === "single" })}>
                  <option value="multi">🔄 Reusable Account Lifecycles</option>
                  <option value="single">1️⃣ Single Global Destruction Event</option>
                </select>
              </div>

              <button onClick={addCoupon} style={{ background: "#3B1A08", color: "#fff", border: "none", padding: "14px", borderRadius: "10px", cursor: "pointer", fontWeight: "600", marginTop: "8px", width: "100%" }}>
                🚀 Launch Automated Matrix Code
              </button>
            </div>
          </div>

          {/* EDIT WORKSPACE PANEL DESIGNS */}
          {editing && (
            <div style={{ background: "#fff", borderRadius: "16px", padding: "28px", border: "2px solid #C4956A", boxShadow: "0 10px 30px rgba(0,0,0,0.05)" }}>
              <h3 style={{ margin: "0 0 20px 0" }}>✏️ Adjust Configuration Matrix</h3>
              <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
                <input style={formInputStyle} value={editCoupon.code || ""} onChange={(e) => setEditCoupon({ ...editCoupon, code: e.target.value.toUpperCase() })} />
                <select style={formInputStyle} value={editCoupon.audienceType || "all"} onChange={(e) => setEditCoupon({ ...editCoupon, audienceType: e.target.value })}>
                  <option value="all">🌐 Open Public</option>
                  <option value="new_users_only">🆕 First-Order Target</option>
                  <option value="specific_user">👤 Customer Target Mapping</option>
                </select>
                {editCoupon.audienceType === "specific_user" && (
                  <input style={formInputStyle} value={editCoupon.targetUserId || ""} onChange={(e) => setEditCoupon({ ...editCoupon, targetUserId: e.target.value })} />
                )}
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
                  <input type="number" style={formInputStyle} value={editCoupon.value || ""} onChange={(e) => setEditCoupon({ ...editCoupon, value: e.target.value })} />
                  <input type="number" style={formInputStyle} value={editCoupon.maxDiscount || ""} onChange={(e) => setEditCoupon({ ...editCoupon, maxDiscount: e.target.value })} />
                </div>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
                  <input type="date" style={formInputStyle} value={editCoupon.starts || ""} onChange={(e) => setEditCoupon({ ...editCoupon, starts: e.target.value })} />
                  <input type="date" style={formInputStyle} value={editCoupon.expires || ""} onChange={(e) => setEditCoupon({ ...editCoupon, expires: e.target.value })} />
                </div>
                <div style={{ display: "flex", gap: "10px" }}>
                  <button onClick={updateCoupon} style={{ flex: 1, background: "#2E7D32", color: "#fff", border: "none", padding: "12px", borderRadius: "8px", cursor: "pointer", fontWeight: "600" }}>💾 Commit Changes</button>
                  <button onClick={() => setEditing(null)} style={{ background: "#FAF6F0", border: "1px solid #DCD1C4", padding: "12px", borderRadius: "8px", cursor: "pointer" }}>Cancel</button>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* DISPLAY PIPELINE WORKSPACE FOR DYNAMIC REPOSITORIES */}
        <div style={{ gridColumn: "span 2" }}>
          
          {/* MASTER SEARCH & INTERACTIVE BATCH PROCESSING HUD HEADER */}
          <div style={{ background: "#fff", borderRadius: "16px", padding: "24px", border: "1px solid #EAE1D4", marginBottom: "25px", boxShadow: "0 4px 20px rgba(0,0,0,0.01)" }}>
            <div style={{ display: "flex", gap: "15px", marginBottom: "20px", flexWrap: "wrap" }}>
              <input type="text" placeholder="🔍 Search unique parameter code indices..." value={search} onChange={(e) => setSearch(e.target.value)} style={{ ...formInputStyle, flex: 1, minWidth: "250px" }} />
              
              <select value={filter} onChange={(e) => setFilter(e.target.value)} style={{ ...formInputStyle, width: "auto" }}>
                <option value="All">All Structural Filters</option>
                <option value="Active">Active Loop States</option>
                <option value="Disabled">Disabled Isolation States</option>
                <option value="Expired">Past Horizon Expirations</option>
              </select>

              <select value={sortBy} onChange={(e) => setSortBy(e.target.value)} style={{ ...formInputStyle, width: "auto" }}>
                <option value="newest">📅 Array Order: Newest Created</option>
                <option value="code">🔤 Alphabetical Match (A-Z)</option>
                <option value="used">🔥 Volumetric Redemptions</option>
                <option value="expiry">⏳ Critical Lifespans First</option>
              </select>

              <button onClick={handleExportToCSV} style={{ padding: "12px 18px", borderRadius: "10px", background: "#FAF6F0", border: "1px solid #DCD1C4", cursor: "pointer", fontWeight: "600", fontSize: "13px" }}>
                📥 Export Sheet (.CSV)
              </button>
            </div>

            {/* INTERACTIVE BULK ACTION TOOLBAR DRAW PANEL */}
            {selectedCouponIds.length > 0 && (
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", background: "#FAF6F0", border: "1px solid #C4956A", padding: "14px 20px", borderRadius: "10px", transition: "all 0.3s" }}>
                <span style={{ fontSize: "14px", fontWeight: "600", color: "#3B1A08" }}>⚡ Batch Queue Execution Group: <strong>{selectedCouponIds.length}</strong> items checked</span>
                <div style={{ display: "flex", gap: "10px" }}>
                  <button onClick={() => handleBulkActivationToggle(true)} style={{ padding: "8px 14px", background: "#2E7D32", color: "#fff", border: "none", borderRadius: "6px", cursor: "pointer", fontSize: "12px", fontWeight: "600" }}>🟢 Bulk Enable</button>
                  <button onClick={() => handleBulkActivationToggle(false)} style={{ padding: "8px 14px", background: "#F5B942", color: "#fff", border: "none", borderRadius: "6px", cursor: "pointer", fontSize: "12px", fontWeight: "600" }}>🟡 Bulk Disable</button>
                  <button onClick={handleBulkPurge} style={{ padding: "8px 14px", background: "#D32F2F", color: "#fff", border: "none", borderRadius: "6px", cursor: "pointer", fontSize: "12px", fontWeight: "600" }}>🔴 Permanent Bulk Delete</button>
                  <button onClick={() => setSelectedCouponIds([])} style={{ padding: "8px 12px", background: "#none", border: "1px solid #DCD1C4", color: "#544E48", borderRadius: "6px", cursor: "pointer", fontSize: "12px" }}>Cancel</button>
                </div>
              </div>
            )}
          </div>

          {/* DYNAMIC CARD VIEW GENERATION GRID LOOP */}
          {loading ? (
            <p>Syncing secure data channels...</p>
          ) : (
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: "20px", marginBottom: "40px" }}>
              {safeCoupons
                .filter((c) => (c?.code || "").toLowerCase().includes(search.toLowerCase()) && (filter === "All" || (filter === "Active" ? c?.active : !c?.active)))
                .sort((a, b) => sortBy === "code" ? (a?.code || "").localeCompare(b?.code || "") : sortBy === "used" ? (b?.usageCount || 0) - (a?.usageCount || 0) : (b?.createdAt?.seconds || 0) - (a?.createdAt?.seconds || 0))
                .map((coupon) => {
                  const styleSheet = getCategoryColor(coupon?.category);
                  const timeSpecs = getExpiryStatus(coupon?.expires, coupon?.starts);
                  const selectCheck = selectedCouponIds.includes(coupon.id);

                  return (
                    <div key={coupon.id} style={{ background: styleSheet.cardBg, borderRadius: "16px", padding: "24px", border: selectCheck ? "2px solid #4F46E5" : `1px solid ${styleSheet.border}`, boxShadow: "0 6px 18px rgba(0,0,0,0.02)", display: "flex", flexDirection: "column", justifyContent: "space-between", position: "relative" }}>
                      
                      {/* Selection Box & Clipboard Hook Area */}
                      <div>
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "14px" }}>
                          <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                            <input type="checkbox" checked={selectCheck} onChange={() => toggleSelectCoupon(coupon.id)} style={{ width: "16px", height: "16px", cursor: "pointer" }} />
                            
                            <div style={{ position: "relative" }}>
                              <h2 onClick={() => copyToClipboard(coupon?.code)} style={{ margin: 0, fontFamily: "monospace", fontSize: "22px", color: "#1E1B18", cursor: "pointer", fontWeight: "700" }} title="Click to copy parameter token">
                                {coupon?.code || "UNNAMED"} 📋
                              </h2>
                              {copiedCode === coupon?.code && (
                                <span style={{ position: "absolute", top: "-24px", left: 0, background: "#1E1B18", color: "#fff", fontSize: "10px", padding: "2px 6px", borderRadius: "4px" }}>Copied!</span>
                              )}
                            </div>
                          </div>

                          <span style={{ background: coupon?.active ? "#E8F5E9" : "#FFEBEE", color: coupon?.active ? "#2E7D32" : "#C62828", padding: "4px 10px", borderRadius: "20px", fontWeight: "700", fontSize: "12px" }}>
                            {coupon?.active ? "● Active" : "○ Offline"}
                          </span>
                        </div>

                        {/* Tag Badges Metrics Panel */}
                        <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginBottom: "14px" }}>
                          <span style={{ fontSize: "11px", fontWeight: "700", padding: "4px 8px", borderRadius: "4px", background: styleSheet.bg, color: styleSheet.color, textTransform: "uppercase" }}>
                            {coupon?.category || "General"}
                          </span>
                          <span style={{ fontSize: "11px", fontWeight: "600", padding: "4px 8px", borderRadius: "4px", background: "#FAF6F0", color: "#544E48" }}>
                            {coupon?.audienceType === "specific_user" ? `👤 Only: ${coupon?.targetUserId}` : coupon?.audienceType === "new_users_only" ? "🆕 First-Order" : "🌐 Open Tier"}
                          </span>

                          {/* DYNAMIC TIMEFRAME BADGE RENDERS */}
                          {timeSpecs.variant === "expired" && <span style={{ fontSize: "11px", fontWeight: "700", padding: "4px 8px", borderRadius: "4px", background: "#D32F2F", color: "#fff" }}>🚨 EXPIRED</span>}
                          {timeSpecs.variant === "warning" && <span style={{ fontSize: "11px", fontWeight: "700", padding: "4px 8px", borderRadius: "4px", background: "#FF9800", color: "#fff" }}>⏳ EXPIRING SOON</span>}
                        </div>

                        {/* Technical Configuration Specifications */}
                        <div style={{ fontSize: "14px", display: "flex", flexDirection: "column", gap: "6px", color: "#3B342E" }}>
                          <p style={{ margin: 0 }}><strong>Benefit Yield:</strong> {coupon?.type === "percentage" ? `${coupon?.value}% Off` : `₹${coupon?.value} Off`}{coupon?.type === "percentage" && Number(coupon?.maxDiscount) > 0 && ` (Max ₹${coupon?.maxDiscount})`}</p>
                          <p style={{ margin: 0 }}><strong>Minimum Trigger:</strong> ₹{coupon?.minOrder}</p>
                          <p style={{ margin: 0 }}><strong>Redemption Vol Cap:</strong> {coupon?.usageCount || 0} / {coupon?.usageLimit || "∞"}</p>
                          <p style={{ margin: 0 }}><strong>Target Lifecycle:</strong> {coupon?.singleUse ? "Global Single Use" : "Reusable Pattern"}</p>
                        </div>

                        {/* DYNAMIC PROGRESS ACCELERATOR GRAPH PROGRESS SLIDER */}
                        {Number(coupon?.usageLimit) > 0 && (
                          <div style={{ marginTop: "15px", marginBottom: "15px" }}>
                            <div style={{ display: "flex", justifyContent: "space-between", fontSize: "11px", color: "#8A827C", marginBottom: "4px" }}>
                              <span>Campaign Consumption Velocity</span>
                              <strong>{Math.round(((coupon?.usageCount || 0) / coupon.usageLimit) * 100)}%</strong>
                            </div>
                            <div style={{ width: "100%", height: "6px", background: "#FAF6F0", borderRadius: "10px", border: "1px solid #EAE1D4", overflow: "hidden" }}>
                              <div style={{ height: "100%", background: coupon?.active ? "#3B1A08" : "#A8A096", width: `${Math.min(((coupon?.usageCount || 0) / coupon.usageLimit) * 100, 100)}%`, transition: "width 0.4s ease" }} />
                            </div>
                          </div>
                        )}

                        <p style={{ fontWeight: "600", fontSize: "12px", marginTop: "12px", color: timeSpecs.variant === "expired" ? "#D32F2F" : "#C4956A" }}>
                          {timeSpecs.label}
                        </p>
                      </div>

                      {/* Bottom Level Operation Drawers */}
                      <div style={{ display: "flex", gap: "8px", marginTop: "18px", borderTop: "1px dashed #DCD1C4", paddingTop: "14px" }}>
                        <button onClick={() => toggleCoupon(coupon)} style={{ flex: 1, background: coupon?.active ? "#F5B942" : "#2E7D32", color: "#fff", border: "none", padding: "10px", borderRadius: "8px", cursor: "pointer", fontWeight: "600", fontSize: "13px" }}>
                          {coupon?.active ? "Disable" : "Enable"}
                        </button>
                        
                        <button 
                          onClick={() => { 
                            setEditing(coupon); 
                            setEditCoupon({
                              code: coupon?.code || "",
                              type: coupon?.type || "percentage",
                              value: coupon?.value || "",
                              maxDiscount: coupon?.maxDiscount || "",
                              minOrder: coupon?.minOrder || "",
                              category: coupon?.category || "General",
                              starts: coupon?.starts || "",
                              expires: coupon?.expires || "",
                              usageLimit: coupon?.usageLimit || "",
                              perUserLimit: coupon?.perUserLimit || 1,
                              singleUse: coupon?.singleUse || false,
                              audienceType: coupon?.audienceType || "all",
                              targetUserId: coupon?.targetUserId || "",
                              triggerType: coupon?.triggerType || "manual"
                            }); 
                          }} 
                          style={{ flex: 1, background: "#C4956A", color: "#fff", border: "none", padding: "10px", borderRadius: "8px", cursor: "pointer", fontWeight: "600", fontSize: "13px" }}
                        >
                          ✏️ Parameters
                        </button>

                        <button onClick={() => deleteCoupon(coupon.id)} style={{ background: "#FFEBEE", color: "#C62828", border: "1px solid #FFCDD2", padding: "10px 14px", borderRadius: "8px", cursor: "pointer" }}>
                          🗑️
                        </button>
                      </div>

                    </div>
                  );
                })}
            </div>
          )}

          {/* DYNAMIC HISTORICAL DATA AUDIT LOG DATAGRID TABLE */}
          <div style={{ background: "#fff", borderRadius: "16px", padding: "24px", border: "1px solid #EAE1D4", boxShadow: "0 4px 20px rgba(0,0,0,0.01)" }}>
            <h3 style={{ margin: "0 0 6px 0", fontSize: "16px", fontWeight: "700" }}>📜 Permanent Coupon System Audit Log</h3>
            <p style={{ color: "#8A827C", fontSize: "13px", margin: "0 0 20px 0" }}>Real-time tracing of deployment loops, administrative parameter mutations, and state resets.</p>
            
            <div style={{ overflowX: "auto", maxHeight: "280px" }}>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "13px" }}>
                <thead>
                  <tr style={{ background: "#FAF6F0", borderBottom: "1px solid #EAE1D4", color: "#544E48" }}>
                    <th style={{ padding: "12px", textAlign: "left" }}>Timestamp Trigger</th>
                    <th style={{ padding: "12px", textAlign: "left" }}>Target Subject</th>
                    <th style={{ padding: "12px", textAlign: "left" }}>Action Signature</th>
                    <th style={{ padding: "12px", textAlign: "left" }}>Parameter Meta Scope</th>
                  </tr>
                </thead>
                <tbody>
                  {safeLogs.length === 0 ? (
                    <tr>
                      <td colSpan="4" style={{ padding: "20px", textAlign: "center", color: "#A8A096" }}>No active logs stored in current execution pipelines.</td>
                    </tr>
                  ) : (
                    safeLogs.map((log) => (
                      <tr key={log?.id || Math.random()} style={{ borderBottom: "1px solid #FAF6F0" }}>
                        <td style={{ padding: "12px", color: "#544E48" }}>{log?.timestamp?.seconds ? new Date(log.timestamp.seconds * 1000).toLocaleString() : "Sync Processing"}</td>
                        <td style={{ padding: "12px", fontWeight: "700", fontFamily: "monospace" }}>{log?.code || "SYSTEM"}</td>
                        <td style={{ padding: "12px" }}>
                          <span style={{ padding: "4px 8px", borderRadius: "4px", fontSize: "11px", fontWeight: "700", background: log?.action?.includes("CREATE") ? "#E8F5E9" : log?.action?.includes("PURGE") || log?.action?.includes("DELETE") ? "#FFEBEE" : "#FFF3E0", color: log?.action?.includes("CREATE") ? "#1B5E20" : log?.action?.includes("PURGE") || log?.action?.includes("DELETE") ? "#C62828" : "#E65100" }}>
                            {log?.action || "LOG_EVENT"}
                          </span>
                        </td>
                        <td style={{ padding: "12px", color: "#8A827C" }}>{log?.category ? `${log?.category} Framework` : "Metadata Config Sync Override"}</td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
